### ISSUE TITLE
No provider for ControlContainer!

### ISSUE THREAD

**Issue by gustavolira** [mgechev/angular2-seed#399] opened 2016-01-19 18:48 UTC
Hi,
Today I did a pull at project and now I all angular2 js is loading separeted taking much more time to finish to load the page. 
Another  problem after this is that I'm receiving now this exception "No provider for ControlContainer! (NgControlName -> ControlContainer)" looks like some .js of angular 2 related to NgControl is not being imported.
There's some way to load only angular2 bundle js instead of separeted?

**Comment by NathanWalker** [comment] 2016-01-19 18:54
I haven't seen the `ControlContainer` error, however I also noticed the slow load time with each and every individual js file being loaded separately today with all the latest changes that have been being merged in.
Not sure what is the cause.

**Comment by gustavolira** [comment] 2016-01-19 19:13
Hi @NathanWalker  you will see the error if you use ngControl at your html pages

**Comment by NathanWalker** [comment] 2016-01-19 19:25
@gustavolira To fix that, you have 2 options:
A. in main.ts:
```
import {FORM_PROVIDERS} from 'angular2/common';

// other code here

bootstrap(AppCmp, [
  ROUTER_PROVIDERS,
  provide(LocationStrategy, { useClass: HashLocationStrategy }),
  FORM_PROVIDERS
]);
```

B. in your component that uses the form:
```
import {FORM_PROVIDERS, FORM_DIRECTIVES} from 'angular2/common';
@Component({
  providers: [FORM_PROVIDERS],
  directives: [FORM_DIRECTIVES]
})
```

**Comment by gustavolira** [comment] 2016-01-19 19:36
Hi @NathanWalker  thank you very much for you attention!
I tested both but unfortunately none worked.
I already using ```js directives: [FORM_DIRECTIVES]``` and them I add ```js providers: [FORM_PROVIDERS]``` but with no success

**Comment by NathanWalker** [comment] 2016-01-19 19:45
If you don't mind please copy/paste your entire component here with
template, that would help.

**Comment by gustavolira** [comment] 2016-01-19 19:59
Sure, no problem
This is my login.ts
```typescript
import {Component, Inject} from 'angular2/core';
import {
  FORM_DIRECTIVES,
  FORM_PROVIDERS,
  CORE_DIRECTIVES,
  FormBuilder,
  ControlGroup,
  Validators
} from 'angular2/common';
import {Router} from 'angular2/router';
import {LoginService} from  '../../shared/services/login_service';
import {ViewEncapsulation} from 'angular2/core';


var loginGroupForm = {
  login: ['', Validators.required],
  senha: ['', Validators.required]
};

// Simple component
@Component({
  selector: 'login',
  templateUrl: './login/components/login.html',
  directives: [FORM_DIRECTIVES, CORE_DIRECTIVES],
  providers: [LoginService, FORM_PROVIDERS],
  encapsulation: ViewEncapsulation.None


})

export class LoginCmp {
  loginForm: ControlGroup;

  constructor(public formBuilder: FormBuilder, @Inject(LoginService) public loginService, private router: Router) {
     this.loginForm = formBuilder.group(loginGroupForm);
  }

  onSubmit(object: any): void {
    var json = JSON.stringify(object);

    this.loginService.doLogin(json)
      .subscribe(
        res=> {
          console.log(res.json().token);
          localStorage.setItem('id_token', res.json().token);
          this.router.navigate(['Home']);
        },
        error=> console.log(error)
  );
  }

}
```

This is my html
```HTML
<form action="index.html" id="login-form" class="smart-form client-form" (ngSubmit)="onSubmit(loginForm.value)" [ngFormModel]="loginForm">
            <header>
             Login
            </header>

            <fieldset>
              <section>
                <label class="label">Usuário</label>
                <label class="input"  [class.state-error]="!login.valid && login.touched"> <i class="icon-append fa fa-user"></i>
                  <input type="text" ngControl="login" name="login" #login="ngForm" class="invalid">
                  <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Por favor entre com seu nome de usuário</b>
                </label>
                <em *ngIf="!login.valid && login.touched" for="login" class="invalid">Por favor entre com seu nome de usuário</em>
              </section>
              <section>
                <label class="label">Senha</label>
                <label class="input" [class.state-error]="!senha.valid && senha.touched"> <i class="icon-append fa fa-lock"></i>
                  <input type="password" name="senha" ngControl="senha" #senha="ngForm">
                  <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> Informe sua senha</b>
                </label>
                <em *ngIf="!senha.valid && senha.touched" for="senha" class="invalid">Por favor entre com sua senha</em>
              </section>

              <section>
                <!--<label class="checkbox">
                  <input type="checkbox" name="remember" checked="">
                  <i></i>Stay signed in</label>-->
              </section>
            </fieldset>
            <footer>
              <button type="submit" class="btn btn-primary" [disabled]="!loginForm.valid">
                Acessar
              </button>
            </footer>
          </form>

```

**Comment by NathanWalker** [comment] 2016-01-19 20:34
Hmm, looks right at first glance. You should probably remove `action="index.html"` from the form and have you tried putting `FORM_PROVIDERS` on your bootstrap instead of directly in the component here as well?

**Comment by gustavolira** [comment] 2016-01-19 20:36
Yes I tried, after pull these works like a charm

**Comment by NathanWalker** [comment] 2016-01-19 20:38
Oh excellent :+1:

**Comment by gustavolira** [comment] 2016-01-19 20:38
Sorry I write wrong, BEFORE PULL these works like a charm

**Comment by NathanWalker** [comment] 2016-01-19 20:39
I'm going to separate out your other concern about the separated js loading into another issue.

**Comment by gustavolira** [comment] 2016-01-19 20:42
Thank you very much @NathanWalker and sorry for my mistake

**Comment by NathanWalker** [comment] 2016-01-19 20:43
Not sure what's going on with your setup. Someone else may see something that may help you.

**Comment by mgechev** [comment] 2016-01-20 16:06
Lets close this issue since it doesn't seems related to the seed.

@gustavolira thanks for pointing out the show load of dev! Thats the fix https://github.com/mgechev/angular2-seed/commit/7cd0653b5e74b24ed13e6fffb69284a77abf56a3. We're only waiting for beta.2 to allow us merge it.

**Closed** 2016-01-20 16:07 UTC

**Comment by gustavolira** [comment] 2016-01-20 16:19
@mgechev Anyway thank you for your attention.
What is strange is that this exception only started happening after I updated my angular2-seed project.
I will try figure out this

**Comment by mgechev** [comment] 2016-01-20 16:22
@gustavolira what changes did the update introduce? Change of Angular 2's version?

**Comment by gustavolira** [comment] 2016-01-20 18:31
Hi @mgechev I just change 2.0.0-beta.1 to 2.0.0-beta.0 and now is working again.
I found someone with same problem with beta.1 https://github.com/angular/angular/issues/6374
Thank you for your attention and patience
