### ISSUE TITLE
Import order of scss files incorrect

### ISSUE THREAD

**Issue by gempir** [mgechev/angular2-seed#1132] opened 2016-07-17 09:33 UTC
**Steps to reproduce and a minimal demo of the problem**
1. Enable SCSS support for your project
2. Create a mixin or variable in src/client/css and use it in a component scss file

**Current behavior**
Throwing Error mixin/variable doesn't exist

**Expected/desired behavior**
Using the mixin/variable from src/client/css without errors

I believe this is an Issue how gulp concat's the files, because If i'm not mistaken src/client/css should be one of the first files loaded and I see no other place where you would put your mixins.

**Comment by TheDonDope** [comment] 2016-07-18 12:03
Paging @hank-ehly: Do you have thoughts on this?

**Comment by hank-ehly** [comment] 2016-07-18 23:01
@gempir 

Thanks for your comment.

Just to clarify, am I correct in understanding that you're able to use sass variables and mixins in your project, but the console does show and "undefined variable" error?

**Comment by gempir** [comment] 2016-07-20 09:02
@hank-ehly No. I can't use mixins or variables at all AND the console will also show a "Undefined variable:..." error

**Comment by iherbivore** [comment] 2016-07-22 20:10
My sass config works like this:

```
this.PLUGIN_CONFIGS['gulp-sass'] = {
      includePaths: [
        './node_modules/bootstrap-sass/assets/stylesheets',
        './node_modules/font-awesome/scss',
        './src/client/css'
      ]
    };
```

A month or so back, the sass plugin changed its behavior. It used to accumulate visited folders into includePaths. Since src/client/css is one of the first visited this worked fine.  No you must explicitly add it if that is where your variables are.

**Comment by gempir** [comment] 2016-07-22 20:18
@iherbivore I'm sorry but where is that config located you are talking about? I can't seem to find something similar in the project.

**Comment by tarlepp** [comment] 2016-07-22 20:20
Also is there a way to process all sass/scss files first from node_modules? So that we don't need to define all of those invidually.

**Comment by iherbivore** [comment] 2016-07-22 20:22
The original config is in the `tools/config/seed.config.ts`

```
 PLUGIN_CONFIGS: any = {
   ...
    /**
     * The options to pass to gulp-sass (and then to node-sass).
     * Reference: https://github.com/sass/node-sass#options
     * @type {object}
     */
    'gulp-sass': {
      includePaths: ['./node_modules/']
    },
```

The version I posted above goes in the `tools/config/project.config.ts` to overwrite the default.

**Comment by iherbivore** [comment] 2016-07-22 20:25
@tarlepp The separate node_modules entries I have are probably not needed... that is just how I got it working before sass was supported by the seed.

**Comment by gempir** [comment] 2016-07-22 20:29
@iherbivore that's weird I don't have the gulp-sass config in my seed.config but adding it in seed or overwriting it in project.config doesn't solve my variable issue, sadly.

**Comment by iherbivore** [comment] 2016-07-22 20:31
@gempir Perhaps you need to update your seed? See it is here: https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L453

**Comment by gempir** [comment] 2016-07-22 20:45
@iherbivore alright!  yeah my version was a few days outdated. Varibles now work, although I can't get the error message to disappear from my console. Works anyway though.

**Comment by iherbivore** [comment] 2016-07-22 20:51
I think we have reached the end of useful things I can contribute. I did fail to point out that the PLUGIN_CONFIGS goes inside the constructor.   Maybe try changing it in the seed.config.ts file instead as a test? Good luck!

**Comment by gempir** [comment] 2016-07-22 21:00
@iherbivore yeah I know already had it there.  Thanks for the help anyway

**Comment by gempir** [comment] 2016-08-02 19:40
can nobody reproduce this? 

I'm still having this issue.

**Comment by mgechev** [comment] 2016-08-20 22:58
I'm not able to do so. Lets close this issue for now and reopen it if someone reproduces it again.

**Closed by mgechev** 2016-08-20 22:58 UTC
