### ISSUE TITLE
AOT compilation not working

### ISSUE THREAD

**Issue by nickaranz** [mgechev/angular2-seed#1402] opened 2016-09-28 21:10 UTC
Hello! Thanks for this seed, it is super helpful. I am having an issue with the "compile.ahead.prod" task which is failing to execute.  Just a few days ago this was working for a different project. Today I started a new project by recloning the seed and the AOT proces is failing. I troubleshot it for most of the day but I am fairly new to Angular 2 and Typescript.

**Steps to reproduce and a minimal demo of the problem**
1) clone the current  angular2-seed repo
2) Execute 'npm install' , then 'npm run build.prod.exp'
3) You get this error: 
`Error: undefined, resolving symbol ApplicationModule in {myinstallfolder}/angular2-seed/node_modules/@angular/core/src/application_module.d.ts
    at simplifyInContext (C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\static_reflector.ts:528:15)
    at StaticReflector.simplify (C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\static_reflector.ts:532:18)
    at StaticReflector.annotations (C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\static_reflector.ts:92:28)
    at _loop_1 (C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\codegen.ts:63:48)
    at CodeGenerator.readFileMetadata (C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\codegen.ts:57:22)
    at C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\codegen.ts:105:56
    at Array.map (native)
    at CodeGenerator.codegen (C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\codegen.ts:105:33)
    at codegen ({myinstallfolder}\angular2-seed\tools\tasks\seed\compile.ahead.prod.ts:14:69)
    at Object.main ({myinstallfolder}\tools\@angular\tsc-wrapped\src\main.ts:44:12)
Compilation failed
`

**Other information**
Attached the npm debug log:
[npm-debug.txt](https://github.com/mgechev/angular2-seed/files/499270/npm-debug.txt)

Thank you for any help you can give me

**Comment by mgechev** [comment] 2016-09-28 21:19
Is this a fresh clone of the seed?

**Comment by nickaranz** [comment] 2016-09-28 21:23
Yes, just from this afternoon.

**Comment by mgechev** [comment] 2016-09-28 22:46
Ok. I haven't tried the AoT on Windows actually. I'll be able to take a look at the issue during the weekend.

**Comment by omerfarukyilmaz** [comment] 2016-09-29 06:27
For your information, I just tested now and I could NOT reproduce this error on:

Windows 10.
node -v `v6.5.0`
npm -v `3.10.3`

1) Did a fresh clone.
2) npm install
3) npm run build.prod.exp

I did not get an error. 

`[09:24:24] Finished 'build.index.prod' after 491 ms`
`[09:24:24] Finished 'build.prod.exp' after 49 s`

@nickaranz Of course I can't say why it is not working on your different project, but it should at least work on a fresh clone.

**Comment by nickaranz** [comment] 2016-09-29 15:07
Thank you for trying it out @omerfarukyilmaz - I just asked a couple other coworkers to do a fresh clone, install and run a build.prod.exp - We all received the same error `Error: undefined, resolving symbol ApplicationModule` Other details, we are all using Windows, two of the test computers were Windows 8.1 Enterprise and another one was a  Windows Server 2012 VM. I'll do some more troubleshooting tonight and try it on a WIN10 OS. Thank you for your help

**Comment by i7326** [comment] 2016-09-29 17:19
@nickaranz Do you have latest tsc atleast 2.0+ ??

**Comment by goodfield** [comment] 2016-09-29 17:47
just had the same problem, found this issue, updated tsc from 1.8x to 2.0x ... no it works!

**Comment by nikhiln** [comment] 2016-09-30 08:55
I am able to reproduce this error on following:

Ubuntu `14.04`
node -v `4.5.0`
npm -v `2.15.9`

tsc -v `2.0.3`

**Comment by mgechev** [comment] 2016-09-30 14:41
The seed uses the local tsc (the one installed in the angular2-seed directory). You can verify what version is it by running "./node_modules/.bin/tsc --version".

**Comment by Delagen** [comment] 2016-09-30 15:08
node is old, I am facing issues with Typescript on windows even with 6.2.0, installing 6.5.0 fixed problem

**Comment by i7326** [comment] 2016-09-30 15:44
node -v
v6.3.1

npm -v
3.10.3

tsc -v
Version 2.1.0-dev.20160922

OS : Windows 10
AoT works good in this env .

**Comment by mgechev** [comment] 2016-09-30 15:56
Thanks for the feedback. It seems like an environment specific issue so we can close it.

**Closed by mgechev** 2016-09-30 15:56 UTC

**Comment by nickaranz** [comment] 2016-10-06 21:39
Thank you all for your suggestions. In case it helps someone in the future, I was able to fix my issue in Wndows with a combo of two things:
- Upgrading node to v6.7.0 (it seems to work on anything 6.5.0+ )
- Removing this PATH from my environment variables `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\` - it  got added with an old TypeScript pluging for Visual Studio 2013

**Comment by mgechev** [comment] 2016-10-06 22:02
@nickaranz thanks for sharing!

**Comment by dhardtke** [comment] 2016-10-10 01:08
I'm having the same issue and would be very grateful if someone could point me in the right direction.

I have the latest versions of all dependencies installed, that is:
- typescript 2.0.3
- webpack 2.1.0-beta.25
- @angular/compiler-cli 0.6.4
- @angular/platform-server 2.0.2
- @ngtools/webpack 1.1.0

**Comment by mgechev** [comment] 2016-10-10 01:28
@dhardtke angular-seed does not use webpack, as you can see from the readme file. Most likely your issue doesn't belong to this repository.

**Comment by dhardtke** [comment] 2016-10-10 01:54
Oh you're right, I will create an issue in the appropriate repository right away.
Thanks!

**Comment by inska** [comment] 2016-10-25 09:31
Similar issue here.
Does right "iminar\Dev\angular" blah blah path on error? iminar might be https://github.com/IgorMinar .. and similar error shown when I tried to run command ng build with --aot option.
