### ISSUE TITLE
Add Sass support - css source mapping

### ISSUE THREAD

**Issue by DanPii** [mgechev/angular2-seed#779] opened 2016-04-19 09:04 UTC
Hi,
i've cloned your seed and followed the wiki description to add sass support (https://github.com/mgechev/angular2-seed/wiki/Add-Sass-support). The scss files are compiled correctly, but css source mapping is only working for main.scss.

Component scss files are compiled and copied into the corresponding folder, e.g. "dist/dev/app/+home/components/home.component.css".
But when running dev mode (npm start),it seems all component css is injected as < style > tag and css source mapping doesn't work for me.

How could I get css source mapping work for component scss/css files. I think the same problem should also occur if sass support is not added.

**Comment by mgechev** [comment] 2016-04-19 09:56
Angular injects the component-specific CSS files in `<style>` elements.

**Comment by DanPii** [comment] 2016-04-19 11:18
is there a way to have a source mapping for these `<stlye>` elements to the original css files?

**Comment by d3viant0ne** [comment] 2016-04-19 14:54
@DanPii - @nareshbhatia run a fork devoted to extending the seed to use the sass pre-compiler here https://github.com/archfirst/angular2-seed-sass

**Comment by d3viant0ne** [comment] 2016-04-19 14:56
On a more personal note, I have moved away from sass proper and opted to instead use a mix of precss & postcss features to retain the functionality without the headache of inlining sass/scss in my templates.

IMO it's worth considering

**Comment by DanPii** [comment] 2016-04-19 21:49
@d3viant0ne i found your angular2-seed-postcss fork today and read some other opinions about postcss over sass. it really seems worth considering. I've got a sass project already that i would need to port to postcss, so i will check if all features are supported and how much changes are needed.

I've cloned @nareshbhatia [angular2-seed-sass](https://github.com/archfirst/angular2-seed-sass) as well as your [postcss ](https://github.com/DeviantJS/angular2-seed-postcss)fork. As mentioned by @mgechev Angular injects component css files as `<style>` elements. So source mapping is not working for this as well.
@d3viant0ne Do you know a way to get source mapping working on Angular2's inline style?

**Comment by d3viant0ne** [comment] 2016-04-19 22:12
@DanPii - I tried for about a week to get it to work properly before I switched directions (postcss)

@nareshbhatia is in the same place that I was stuck on, the zone.js errors.

If I have some time this weekend, I may circle back around to it for the sake of not losing to software but given the performance gains I got out of postcss with 90% of the functionality it's honestly not terribly high on my list.

The path to get it working will require a function call to process your sass into css when the template is inlined but that runs your into zone.js throwing. Given Angular2's push towards RC, I unfortunately don't see whatever the issue is being resolved anytime soon.

Assuming I have the time this weekend, i'm going to work the issue on @nareshbhatia 's fork where he has an open issue archfirst/angular2-seed-sass#8 so we can focus everyones effort on the problem in the same place.

**Comment by DanPii** [comment] 2016-04-20 00:35
@d3viant0ne thanks for the feedback. I'm still new to Angular and gulp tasks. 
But if I understand it correctly, shouldn't the source mapping problem apply to pure css (no SASS, no postcss) as well, because Angular injects component css files as inline style? Or is there another way?

**Comment by d3viant0ne** [comment] 2016-04-20 01:49
It's not so much about the component style at this point zone.js blows up trying to load the template.

```js
  About component
    ✖ should work
      Chrome 49.0.2623 (Mac OS X 10.11.4)
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    Failed: Failed to load /Users/nbhati/projects/angular2-seed-sass/dist/dev/about/components/about.component.html
    invoke@/Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:308:34
    run@/Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:201:50
    /Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:553:61
    invokeTask@/Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:341:43
    runTask@/Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:238:58
    drainMicroTaskQueue@/Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:459:43
```

**Comment by d3viant0ne** [comment] 2016-04-20 01:51
The generated files are all properly created and in the proper place, it just blows up.

**Comment by mgechev** [comment] 2016-04-20 06:01
As not seed specific issue, we can close it for now.

**Closed by mgechev** 2016-04-20 06:01 UTC
Labels: question

**Comment by smartm0use** [comment] 2016-07-21 15:45
Hello, i created the following Gulp tasks:

gulp.task('styles', function(cb) {
    return gulp.src('src/app/**/*.scss') //
        .pipe(sourcemaps.init())
        .pipe(sass())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest(paths.dist + '/app/'));
});

But i can't see any source maps in inspection tools of Chrome. What could be the problem?
