### ISSUE TITLE
Fonts Error - Failed to decode downloaded font

### ISSUE THREAD

**Issue by ivayloc** [mgechev/angular2-seed#1375] opened 2016-09-22 14:52 UTC
I have added `/fonts` folder in the `assets` folder, and a `@font-face` in my css: 

```css
@font-face {
        font-family: "Montserrat-UltraLight";
        font-style: normal;
        font-weight: 600;
        src: url("../fonts/Montserrat-UltraLight/Montserrat-UltraLight.eot?#iefix") format("embedded-opentype"), 
              url("../fonts/Montserrat-UltraLight/Montserrat-UltraLight.woff2") format("woff2"), 
              url("../fonts/Montserrat-UltraLight/Montserrat-UltraLight.woff") format("woff"), 
              url("../fonts/Montserrat-UltraLight/Montserrat-UltraLight.ttf") format("truetype"), 
              url("../fonts/Montserrat-UltraLight/Montserrat-UltraLight.svg#Montserrat-UltraLight") format("svg"); 
}
```
but when the site loads this error appears in Chrome console
```
Failed to decode downloaded font: http://localhost:5555/fonts/Montserrat-UltraLight/Montserrat-UltraLight.woff2
VM59:1 OTS parsing error: invalid version tag
VM59:1 Failed to decode downloaded font: http://localhost:5555/fonts/Montserrat-UltraLight/Montserrat-UltraLight.woff2
VM59:1 OTS parsing error: invalid version tag
VM59:1 Failed to decode downloaded font: http://localhost:5555/fonts/Montserrat-UltraLight/Montserrat-UltraLight.woff
VM59:1 OTS parsing error: invalid version tag
VM59:1 Failed to decode downloaded font: http://localhost:5555/fonts/Montserrat-UltraLight/Montserrat-UltraLight.woff
VM59:1 OTS parsing error: invalid version tag
VM59:1 Failed to decode downloaded font: http://localhost:5555/fonts/Montserrat-UltraLight/Montserrat-UltraLight.ttf
VM59:1 OTS parsing error: invalid version tag
VM59:1 Failed to decode downloaded font: http://localhost:5555/fonts/Montserrat-UltraLight/Montserrat-UltraLight.ttf
VM59:1 OTS parsing error: invalid version tag
```

with a `Content-Type: text/html; charset=UTF-8` which is also not correct

**Comment by martingula** [comment] 2016-09-22 14:56
I have same issue

**Comment by mgechev** [comment] 2016-09-22 15:08
This is caused by BtowserSync. It seems overwriting the paths and disabling the dot rule has more drawbacks than possitives. Today I will revert it back and everything should work.

**Comment by mgechev** [comment] 2016-09-22 18:28
Fixed in master.

**Closed by mgechev** 2016-09-22 18:28 UTC
