### ISSUE TITLE
Cannot load JavaScript library without typings after production build 

### ISSUE THREAD

**Issue by ZuSe** [mgechev/angular2-seed#1069] opened 2016-07-01 10:17 UTC
After doing a production build my app complains about not defined variables provided by typeless libs that were added to the project.  I dunno if this is a bug or if I have overseen anything, so sorry in case of a wrong report, but I can't explain at the moment why it does not behave as you would expect.

**Steps to reproduce and a minimal demo of the problem**
Get the current master and add swampdragon to your dependencies (available via npm)
e.g. in my project.config.ts i put:
```
let additional_deps:InjectableDependency[] = [
      {src: 'swampdragon/dist/swampdragon.js', inject: 'libs'},
```
Next, create a new class (component or service) and declare swampdragon as variable outside of it (needed for TSC)
`declare var swampdragon:any;`

In the class call any swampdragon method like:
` swampdragon.ready(() => {
      this._logger.debug('SwamDragon is ready');
    });`

_What steps should we try in your demo to see the problem?_

Run gulp serve.dev (npm start) -> Everything works fine.
Run gulp serve.prod -> An Expection is thrown

**Current behavior**

> shims.js?1467365279832:12 Uncaught TypeError: System.registerDynamic is not a function(anonymous function) @ shims.js?1467365279832:12
> app.js?1467365279833:41759 Uncaught ReferenceError: swampdragon is not defined

**Expected/desired behavior**

It should actually load the application and resolve swampdragon as it is defined in shims.js.

So the question:
Can there be a bug in the production build process when dealing with JS without having typings?

**Comment by mgechev** [comment] 2016-07-04 07:33
Duplicate of https://github.com/mgechev/angular2-seed/issues/1052.

**Closed by mgechev** 2016-07-04 07:33 UTC
