### ISSUE TITLE
serve.coverage fail on filter and promise

### ISSUE THREAD

**Issue by OlivierMary** [mgechev/angular2-seed#716] opened 2016-04-04 21:45 UTC
Hi,

**Steps to reproduce and a minimal demo of the problem**

Change `src/home/components/home.component.ts` to :
```typescript
import {Component, OnInit } from 'angular2/core';
import {CORE_DIRECTIVES, FORM_DIRECTIVES} from 'angular2/common';

import {NameListService} from '../../shared/services/name-list.service';

@Component({
  selector: 'sd-home',
  moduleId: module.id,
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  directives: [FORM_DIRECTIVES, CORE_DIRECTIVES]
})
export class HomeComponent implements OnInit {


  newName: string;
  constructor(public nameListService: NameListService) {}

 ngOnInit() {
   this.nameListService.get().filter(s=>s.length > 3 ? true : false);
 }
  /*
   * @param newname  any text as input.
   * @returns return false to prevent default form submit behavior to refresh the page.
   */
  addName(): boolean {
    this.nameListService.add(this.newName);
    this.newName = '';
    return false;
  }
}

```

then :

```bash
npm test
npm run serve.coverage
```

**Current behavior**
```bash
$ npm run serve.coverage

> angular2-seed@0.0.0 serve.coverage C:\repositories\angular2-seed
> remap-istanbul -b src/ -i coverage/coverage-final.json -o coverage -t html && npm run gulp -- serve.coverage --color

C:\repositories\angular2-seed\node_modules\istanbul\lib\report\html.js:288
                    text = structuredText[startLine].text;
                                                    ^

TypeError: Cannot read property 'text' of undefined
    at C:\repositories\angular2-seed\node_modules\istanbul\lib\report\html.js:288:53
    at Array.forEach (native)
    at annotateBranches (C:\repositories\angular2-seed\node_modules\istanbul\lib\report\html.js:255:30)
    at HtmlReport.Report.mix.writeDetailPage (C:\repositories\angular2-seed\node_modules\istanbul\lib\report\html.js:426:9)
    at C:\repositories\angular2-seed\node_modules\istanbul\lib\report\html.js:489:26
    at SyncFileWriter.extend.writeFile (C:\repositories\angular2-seed\node_modules\istanbul\lib\util\file-writer.js:57:9)
    at FileWriter.extend.writeFile (C:\repositories\angular2-seed\node_modules\istanbul\lib\util\file-writer.js:147:23)
    at C:\repositories\angular2-seed\node_modules\istanbul\lib\report\html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (C:\repositories\angular2-seed\node_modules\istanbul\lib\report\html.js:482:23)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve.coverage"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 serve.coverage: `remap-istanbul -b src/ -i coverage/coverage-final.json -o coverage -t html && npm run gulp -- serve.coverage --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 serve.coverage script 'remap-istanbul -b src/ -i coverage/coverage-final.json -o coverage -t html && npm run gulp -- serve.coverage --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     remap-istanbul -b src/ -i coverage/coverage-final.json -o coverage -t html && npm run gulp -- serve.coverage --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\repositories\angular2-seed\npm-debug.log

```

**Expected/desired behavior**

No errors & coverage page open.

**Other information**

The `coverage/index.html `is OK until click on `coverage/home/components/home.component.ts.html` or dir/files which have to be generated after this one.

I had the same problem on Promise, maybe not only on this 2 features...

Regards.

**Comment by mgechev** [comment] 2016-04-05 06:32
@OlivierMary thanks for the detailed description! I'll take a look as soon as I can, at first seems like an upstream issue.

**Comment by OlivierMary** [comment] 2016-04-05 16:11
@mgechev tell me if you cant reproduce ;)

**Comment by JohnCashmore** [comment] 2016-04-06 09:18
I am having a similar issue, has a package updated to cause this.

**Comment by TheDonDope** [comment] 2016-04-08 18:03
Hi, this is related to https://github.com/SitePen/remap-istanbul/issues/41 and there is a PR in the pipe to solve this https://github.com/SitePen/remap-istanbul/pull/43 but it hasn't been merged yet.

**Comment by TheDonDope** [comment] 2016-04-15 14:07
Update: The aforementioned issues seemed to be resolved, and remap-istanbul got an update. 
With https://github.com/mgechev/angular2-seed/commit/f274a8570232255971f5ece28eb54fd451d67ad3 being merged in the seed, the issue should be solved now. I'll check it out and post another update on this.

**Comment by OlivierMary** [comment] 2016-04-15 14:44
@TheDonDope I suppose I need to reinstall npm dependencies to try it? or that will take automaticly last commit on remap-istanbul ?

**Comment by TheDonDope** [comment] 2016-04-15 14:48
Hey @OlivierMary, i took the latest commit from the seed (https://github.com/mgechev/angular2-seed/commit/c0b5a76fcfc084f72fce843b27758935cb6c9396) which includes the commit (https://github.com/mgechev/angular2-seed/commit/f274a8570232255971f5ece28eb54fd451d67ad3) which updates `remap-istanbul` to `0.6.1` and did a fresh `npm install`. Then i followed up your reproduction steps and the error still persists.

**Comment by OlivierMary** [comment] 2016-04-15 14:51
Ok @TheDonDope I will try it that at home, will post if I have another behavior !

**Comment by OlivierMary** [comment] 2016-04-16 18:28
Hi, @TheDonDope same for me, with seed's remap-istanbul version (0.6.1) and with latest 0.6.3.

**Comment by mgechev** [comment] 2016-04-26 10:15
Given https://github.com/SitePen/remap-istanbul/issues/41 it seems the issue is not related to the seed.

Closing it for now.

**Closed by mgechev** 2016-04-26 10:15 UTC
