### ISSUE TITLE
Unable to change port in project.config

### ISSUE THREAD

**Issue by zachallen** [mgechev/angular2-seed#890] opened 2016-05-17 17:37 UTC
I'm attempting to change the port that the application runs on. In project.config.ts I've got:
```
    this.PORT = 3000;
```
However the app continues to start on port 5555.
![bug](https://cloud.githubusercontent.com/assets/3485378/15332659/5f52a11a-1c1b-11e6-96e2-94048c3666b4.png)

**Comment by ludohenin** [comment] 2016-05-17 18:00
@zachallen This is because this value is computed in a config member defined in the parent configuration class (`seed.conf`)
This is something we have to fix for other config members as well.

**Comment by ludohenin** [comment] 2016-05-21 12:11
Closing this one has this actually a duplicate of #823

**Closed by ludohenin** 2016-05-21 12:11 UTC
Labels: duplicate
