### ISSUE TITLE
Test Coverage status remains 100%

### ISSUE THREAD

**Issue by vijayaragavendiran** [mgechev/angular2-seed#844] opened 2016-05-10 12:17 UTC
I have added some new functions and executed the test coverage. The new function doesn't have a spec. But still the test coverage shows 100%. When I navigate to the function in the codecoveage html, I can see the new functions. I am wondering whether I have missed anything. Please guide me.

**Comment by atticae** [comment] 2016-05-10 13:08
I may be wrong, but I think test coverage works only for code you have a spec file for?

**Comment by vijayaragavendiran** [comment] 2016-05-10 16:03
If you have a component with two function and wrote a spec for those will give you 100% coverage. Then  include some additional function to the component. Let say now we have three functions in total. But we have only wrote spec for two function. Now the code coverage for the component should not be 100%. It should be less than 100%. Hope my understanding is write.

**Comment by silentHoo** [comment] 2016-05-12 14:46
@vijayaragavendiran is totally right. Should not be 100%, it would be worthless.

**Comment by manish5377** [comment] 2016-05-12 21:21
+1

Typescript coverage is always showing 100%. Please help.

**Comment by TheDonDope** [comment] 2016-05-16 14:39
Hi @vijayaragavendiran, could you please provide a [SSCCE](http://sscce.org/) or some commit/branch of your fork? I'll take a look at it then.

**Comment by vijayaragavendiran** [comment] 2016-05-18 01:34
Hi @TheDonDope , Please clone the angular2-seed project from github. Add some function as below in home.component.ts.
For Example
===========
getName():string {
    this.nameListService.get();
    return false;
  }

Then run test coverage . You will see the test coverage for home component is 100%.

**Comment by TheDonDope** [comment] 2016-05-18 10:07
Hi @vijayaragavendiran,
thank you for your example! I'll have a look at it later today. However, i think your general problem is not specifically related to the seed itself, but rather either a) the configuration of the coverage tool, or b) the coverage tool itself.

Greetings

Dope

**Comment by vijayaragavendiran** [comment] 2016-05-18 15:24
Hi @TheDonDope
I think its releated to configuration of the coverage tool.

I took a latest code from angular2-seed and made some modification.  Which I have mentioned above.Please see the below steps where it works and not works.

Steps (Code coverage not works)
======================
1.Modify the code i.e. add some new function.
2.Execute 'npm run start'
3.Execute 'npm run test'
4. Execute 'npm run serve.coverage'
5.Istanbul throw the error 
'TypeError: Cannot read property 'text' of undefined
C:\Users\vijaya41399\Documents\Projects\angular2-seed\angular2-seed\node_modules\istanbul\lib\report\html.js:239
                endCol = structuredText[startLine].text.originalLength();'

Steps (Code coverage works)
======================
1.Modify the code i.e. add some new function.
2.Execute 'npm run start'
3.Execute 'npm run test'
4. Instead of executing 'npm run serve.coverag'e. Execute 'npm run start' again.
5. At last execute 'npm run serve.coverage'. Now the code coverage works.

If this is the behavior of the code coverage , then we close this issue. 

Thanks,
Vijay

**Comment by TheDonDope** [comment] 2016-05-18 15:36
Hi Vijay,

thank you for your further analysis! I have one further question: You stated:
> 2. Execute `npm run start` 
> 3. Execute `npm run test`

Do you leave the first shell with the `npm run start` process open and run `npm run test` in a second shell? Or do you close the shell / end the `npm run start` process? I'll have a closer look at it, but my guess is that it might be a configuration related problem (or something of the likes of #716 )

Greetings

Dope

**Comment by vijayaragavendiran** [comment] 2016-05-18 15:54
@TheDonDope 

I used the same shell. But I have ended the start process then executed the test. Hope this might help you.

Thanks,
Vijay

**Comment by TheDonDope** [comment] 2016-05-18 16:01
Hi Vijay,

i could reproduce the behaviour with your instructions, thank your for that! Actually it seems you have found a workaround for #716 🎉  There was an issue opened at the remap-istanbul repo (https://github.com/SitePen/remap-istanbul/issues/41) which has not been resolved yet. 

BUT, since we now have a workaround for this issue, we could tackle it (maybe reconfiguring the `serve.coverage` task or something like that). I will have a closer look into this in the next few days!

Thank you so far!

Greetings

Dope

**Comment by vijayaragavendiran** [comment] 2016-05-18 16:31
@TheDonDope 
Thanks a lot !

Vijay

**Comment by nishesj** [comment] 2016-05-27 08:11
For us the problem was with inlineNg2Template. Fixed by setting target to es5 in 
https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/seed/build.js.test.ts

```
 .pipe(plugins.inlineNg2Template({
      base: APP_SRC,
      useRelativePaths: true
    }))
```
```
 .pipe(plugins.inlineNg2Template({
      base: APP_SRC,
      useRelativePaths: true,
      target: 'es5'
    }))
```

**Comment by mgechev** [comment] 2016-05-29 11:20
@TheDonDope awesome job!

**Comment by mgechev** [comment] 2016-05-30 11:47
We can close this issue since it seems an upstream one, not seed-related.

**Closed by mgechev** 2016-05-30 11:47 UTC
