### ISSUE TITLE
hitting a route in angular 2

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#693] opened 2016-03-27 01:20 UTC
This is an angular 2 question.

``` 
example:

http://my-site/home
```

when i hit the **home** route by writing it in the url bar i get a **404**.

when routing programmatically from angular 2 it works fine. But going directly to it doesn't work.

I've tried different servers with no luck. These include hapijs, python Simplehttpserver and the serve node module.

Is it  a configuration problem?

**Comment by mgechev** [comment] 2016-03-27 09:00
Duplicate of https://github.com/mgechev/angular2-seed/issues/692.

**Closed by mgechev** 2016-03-27 09:00 UTC
