### ISSUE TITLE
npm install failed when requiring external module ts-node/register

### ISSUE THREAD

**Issue by kayue** [mgechev/angular2-seed#225] opened 2015-11-03 14:47 UTC
```
npm install

> angular2-seed@0.0.0 postinstall /Users/kayue/Sites/drop-shipment
> tsd reinstall --clean && tsd link && tsd rebundle && gulp preinstall && gulp postinstall


-> running reinstall

>> written zero files

   >> reflect-metadata (node)

>> nothing rebundled
[22:42:29] Requiring external module ts-node/register

/Users/kayue/Sites/drop-shipment/tools/utils/tasks-tools.ts:32
    readdirSync(path).forEach(function(file) {
                      ^
TypeError: undefined is not a function
    at /Users/kayue/Sites/drop-shipment/tools/utils/tasks-tools.ts:38:47
    at Array.forEach (native)
    at walk (/Users/kayue/Sites/drop-shipment/tools/utils/tasks-tools.ts:32:23)
    at scanDir (/Users/kayue/Sites/drop-shipment/tools/utils/tasks-tools.ts:29:3)
    at Object.autoRegisterTasks (/Users/kayue/Sites/drop-shipment/tools/utils/tasks-tools.ts:10:3)
    at Object.<anonymous> (/Users/kayue/Sites/drop-shipment/gulpfile.ts:13:1)
    at Module._compile (module.js:460:26)
    at Object.loader (/Users/kayue/Sites/drop-shipment/node_modules/ts-node/dist/ts-node.js:94:18)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.14.1
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 postinstall: `tsd reinstall --clean && tsd link && tsd rebundle && gulp preinstall && gulp postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 postinstall script 'tsd reinstall --clean && tsd link && tsd rebundle && gulp preinstall && gulp postinstall'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsd reinstall --clean && tsd link && tsd rebundle && gulp preinstall && gulp postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kayue/Sites/drop-shipment/npm-debug.log
```

**Comment by ludohenin** [comment] 2015-11-03 14:51
This is a duplicate of #195.
Doc needs to be updated as we support from node v4+

**Closed by ludohenin** 2015-11-03 14:51 UTC
