### ISSUE TITLE
OSX Firefox: router-outlet component is not displayed if several times click another tab and refresh browser

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#267] opened 2015-11-28 12:43 UTC
Click tab, refresh browser, repeat this several times and it shows only app component without  `router-outlet` content. There are no any related warnings/errors in console.
<img width="785" alt="screenshot 2015-11-28 15 38 55" src="https://cloud.githubusercontent.com/assets/273313/11451902/69c4af46-95e6-11e5-92a0-f51abce7ecf7.png">

**Comment by mgechev** [comment] 2015-11-28 16:40
Would you clean the cache of the browser and try again? I had the same issue before I did this.

The error you get from livereload is caused by reload of the page. The warning is caused by the es6-shim module.

**Comment by mgechev** [comment] 2015-11-28 16:57
Should be fixed by https://github.com/mgechev/angular2-seed/commit/090bace6a36ec86881927c2e6c4a85e6fdc3bdd4 Let me know if you still can reproduce the issue.

**Closed** 2015-11-28 21:02 UTC

**Comment by tandu** [comment] 2015-11-28 21:27
I have tested, I can't reproduce the issue.
