### ISSUE TITLE
the seed is not working 

### ISSUE THREAD

**Issue by NathanielMalca** [mgechev/angular2-seed#591] opened 2016-03-07 14:35 UTC
just following the simple starting  steps  doesn't work 

```
[16:28:04] Requiring external module ts-node/register
----------------------------------
? Unable to compile TypeScript

gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
gulpfile.ts (2,30): Cannot find module 'run-sequence'. (2307)
tools\config\project.config.ts (1,20): Cannot find module 'path'. (2307)
tools\config\project.config.ts (5,31): Cannot find name 'process'. (2304)
tools\config\seed.config.ts (1,28): Cannot find module 'fs'. (2307)
tools\config\seed.config.ts (2,20): Cannot find module 'yargs'. (2307)
tools\config\seed.config.ts (3,31): Cannot find module 'path'. (2307)
tools\config\seed.config.ts (14,41): Cannot find name '__dirname'. (2304)
tools\config\seed.config.ts (32,31): Cannot find name 'process'. (2304)
tools\config\seed.config.ts (121,50): Cannot find name 'require'. (2304)
tools\manual_typings\seed\merge-stream.d.ts (2,36): Cannot find namespace 'NodeJS'. (2503)
tools\manual_typings\seed\merge-stream.d.ts (3,33): Cannot find namespace 'NodeJS'. (2503)
tools\manual_typings\seed\merge-stream.d.ts (4,17): Cannot find namespace 'NodeJS'. (2503)
tools\manual_typings\seed\systemjs-builder.d.ts (4,60): Cannot find name 'Promise'. (2304)
tools\manual_typings\seed\systemjs-builder.d.ts (5,65): Cannot find name 'Promise'. (2304)
tools\utils\seed\clean.ts (1,23): Cannot find module 'gulp-util'. (2307)
tools\utils\seed\clean.ts (2,24): Cannot find module 'chalk'. (2307)
tools\utils\seed\clean.ts (3,22): Cannot find module 'del'. (2307)
tools\utils\seed\code_change_tools.ts (2,30): Cannot find module 'browser-sync'. (2307)
tools\utils\seed\code_change_tools.ts (17,18): Cannot find name 'require'. (2304)
tools\utils\seed\server.ts (1,26): Cannot find module 'express'. (2307)
tools\utils\seed\server.ts (3,30): Cannot find module 'serve-static'. (2307)
tools\utils\seed\server.ts (5,23): Cannot find module 'path'. (2307)
tools\utils\seed\server.ts (17,25): Cannot find name 'process'. (2304)
tools\utils\seed\server.ts (30,25): Cannot find name 'process'. (2304)
tools\utils\seed\tasks_tools.ts (1,23): Cannot find module 'gulp'. (2307)
tools\utils\seed\tasks_tools.ts (2,23): Cannot find module 'gulp-util'. (2307)
tools\utils\seed\tasks_tools.ts (3,24): Cannot find module 'chalk'. (2307)
tools\utils\seed\tasks_tools.ts (5,50): Cannot find module 'fs'. (2307)
tools\utils\seed\tasks_tools.ts (6,20): Cannot find module 'path'. (2307)
tools\utils\seed\tasks_tools.ts (19,18): Cannot find name 'require'. (2304)
tools\utils\seed\tsproject.ts (1,34): Cannot find module 'gulp-load-plugins'. (2307)
tools\utils\seed\tsproject.ts (9,19): Cannot find name 'require'. (2304)
tools\utils\seed\watch.ts (1,23): Cannot find module 'gulp'. (2307)
tools\utils\seed\watch.ts (2,34): Cannot find module 'gulp-load-plugins'. (2307)
tools\utils\seed\watch.ts (3,20): Cannot find module 'path'. (2307)
----------------------------------

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Nethanel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve.dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nethanel\WebstormProjects\WorldUnited\angular2-seed\npm-debug.log

C:\Users\Nethanel\WebstormProjects\WorldUnited\angular2-seed>npm start

> angular2-seed@0.0.0 start C:\Users\Nethanel\WebstormProjects\WorldUnited\angular2-seed
> gulp serve.dev

[16:31:17] Requiring external module ts-node/register
----------------------------------
? Unable to compile TypeScript

gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
gulpfile.ts (2,30): Cannot find module 'run-sequence'. (2307)
tools\config\project.config.ts (1,20): Cannot find module 'path'. (2307)
tools\config\project.config.ts (5,31): Cannot find name 'process'. (2304)
tools\config\seed.config.ts (1,28): Cannot find module 'fs'. (2307)
tools\config\seed.config.ts (2,20): Cannot find module 'yargs'. (2307)
tools\config\seed.config.ts (3,31): Cannot find module 'path'. (2307)
tools\config\seed.config.ts (14,41): Cannot find name '__dirname'. (2304)
tools\config\seed.config.ts (32,31): Cannot find name 'process'. (2304)
tools\config\seed.config.ts (121,50): Cannot find name 'require'. (2304)
tools\manual_typings\seed\merge-stream.d.ts (2,36): Cannot find namespace 'NodeJS'. (2503)
tools\manual_typings\seed\merge-stream.d.ts (3,33): Cannot find namespace 'NodeJS'. (2503)
tools\manual_typings\seed\merge-stream.d.ts (4,17): Cannot find namespace 'NodeJS'. (2503)
tools\manual_typings\seed\systemjs-builder.d.ts (4,60): Cannot find name 'Promise'. (2304)
tools\manual_typings\seed\systemjs-builder.d.ts (5,65): Cannot find name 'Promise'. (2304)
tools\utils\seed\clean.ts (1,23): Cannot find module 'gulp-util'. (2307)
tools\utils\seed\clean.ts (2,24): Cannot find module 'chalk'. (2307)
tools\utils\seed\clean.ts (3,22): Cannot find module 'del'. (2307)
tools\utils\seed\code_change_tools.ts (2,30): Cannot find module 'browser-sync'. (2307)
tools\utils\seed\code_change_tools.ts (17,18): Cannot find name 'require'. (2304)
tools\utils\seed\server.ts (1,26): Cannot find module 'express'. (2307)
tools\utils\seed\server.ts (3,30): Cannot find module 'serve-static'. (2307)
tools\utils\seed\server.ts (5,23): Cannot find module 'path'. (2307)
tools\utils\seed\server.ts (17,25): Cannot find name 'process'. (2304)
tools\utils\seed\server.ts (30,25): Cannot find name 'process'. (2304)
tools\utils\seed\tasks_tools.ts (1,23): Cannot find module 'gulp'. (2307)
tools\utils\seed\tasks_tools.ts (2,23): Cannot find module 'gulp-util'. (2307)
tools\utils\seed\tasks_tools.ts (3,24): Cannot find module 'chalk'. (2307)
tools\utils\seed\tasks_tools.ts (5,50): Cannot find module 'fs'. (2307)
tools\utils\seed\tasks_tools.ts (6,20): Cannot find module 'path'. (2307)
tools\utils\seed\tasks_tools.ts (19,18): Cannot find name 'require'. (2304)
tools\utils\seed\tsproject.ts (1,34): Cannot find module 'gulp-load-plugins'. (2307)
tools\utils\seed\tsproject.ts (9,19): Cannot find name 'require'. (2304)
tools\utils\seed\watch.ts (1,23): Cannot find module 'gulp'. (2307)
tools\utils\seed\watch.ts (2,34): Cannot find module 'gulp-load-plugins'. (2307)
tools\utils\seed\watch.ts (3,20): Cannot find module 'path'. (2307)
----------------------------------

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Nethanel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve.dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.
```

**Comment by NathanielMalca** [comment] 2016-03-07 15:24
of course i have v4.x.x or higher and npm 2.14.7
ts-node is installed globally 
i use windows 10 and webstorm 11

**Comment by d3viant0ne** [comment] 2016-03-07 15:43
@NathanielMalca - 

Seed works fine on Windows 10 / Node v4.x running latest master
Seed also doesn't require global packages and they generally cause more trouble than the solve.

- I would start with "npm run reinstall"
- If you are running a project on top of seed, I would double check your seed tools === master ( Visual Diff - Beyond Compare works well for this )

**Comment by d3viant0ne** [comment] 2016-03-07 15:44
Also - If this is a public repo, point me to it & i'll take a look.

**Comment by mgechev** [comment] 2016-03-07 15:57
@NathanielMalca also try: 

```
npm cache clean
rm -rf node_modules
rm -rf typings
npm i
npm start
```

**Comment by d3viant0ne** [comment] 2016-03-07 16:05
> npm cache clean
rm -rf node_modules
rm -rf typings
npm i

a.k.a. "npm run reinstall" :)

**Comment by NathanielMalca** [comment] 2016-03-07 16:16
I'm simply trying to start a fresh seed  @d3viant0ne  . tried reinstall - didnt work :/
@mgechev 'rm' is not recognized as an internal or external command,
operable program or batch file. 

What should i do?

**Comment by mgechev** [comment] 2016-03-07 16:27
@d3viant0ne hah, yeah. @NathanielMalca if `npm run reinstall` didn't work there's no point running the script I suggested. Most likely you have problems with `ts-node`.

This issue seems related https://github.com/mgechev/angular2-seed/issues/147.

**Comment by NathanielMalca** [comment] 2016-03-07 16:49
this is the result of the reinstall  @d3viant0ne  @mgechev :
C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed>npm run reinstall

> angular2-seed@0.0.0 reinstall C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed
> npm cache clean && rimraf typings/* && rimraf node_modules/* && npm install

npm WARN optional dep failed, continuing fsevents@1.0.8
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN optional dep failed, continuing fsevents@1.0.8
npm WARN optional dep failed, continuing fsevents@1.0.8
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> phantomjs-prebuilt@2.1.4 install C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at C:\Users\Nethanel\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\Nethanel\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1457368795092\phantomjs-2.1.1-windows -> C:\Users\Nethanel\WebstormProjects\u
ntitled2\angular2-seed\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

> utf-8-validate@1.2.1 install C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_mo
dules\utf-8-validate
> node-gyp rebuild


C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate>if not def
ined npm_config_node_gyp (node "C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
 ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11:116:14)
ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Nethanel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-valida
te
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bufferutil@1.2.1 install C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_module
s\bufferutil
> node-gyp rebuild

\
C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil>if not defined
 npm_config_node_gyp (node "C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
 ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
 command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Nethanel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1

> bufferutil@1.2.1 install C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.
io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

|
C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\n
ode_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" re
build )  else (node  rebuild )
 RR! /configure error
gyp ERR! stack     at failNoPython (C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Nethanel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node
_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
ERR! not ok

> utf-8-validate@1.2.1 install C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\eng
ine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

-
C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\n
ode_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js
" rebuild )  else (node  rebuild )
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Nethanel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node
_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
\
> utf-8-validate@1.2.1 install C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-vali
date
> node-gyp rebuild


C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_
node_gyp (node "C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Nethanel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bufferutil@1.2.1 install C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node
_gyp (node "C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Users\Nethanel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Nethanel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN peerDependencies The peer dependency es6-promise@^3.0.2 included from angular2 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Nethanel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\Nethanel\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json.8bb6c8d913f2626cd5f394345230ae21
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Nethanel\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json.8bb6c8d913f2626cd5f394345230ae21' -> 'C:\Users\Ne
thanel\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\Nethanel\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json.8bb6c8d913f2626cd5f394345230ae21' -> 'C:\User
s\Nethanel\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\Nethanel\\AppData\\Roaming\\npm-cache\\inherits\\2.0.1\\package\\package.json.8bb6c8d913f2626cd5f394345230ae21',
npm ERR!   dest: 'C:\\Users\\Nethanel\\AppData\\Roaming\\npm-cache\\inherits\\2.0.1\\package\\package.json',
npm ERR!   parent: 'http-errors' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Nethanel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "reinstall"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 reinstall: `npm cache clean && rimraf typings/* && rimraf node_modules/* && npm install`
npm ERR! Exit status 4294963248
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 reinstall script 'npm cache clean && rimraf typings/* && rimraf node_modules/* && npm install'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm cache clean && rimraf typings/* && rimraf node_modules/* && npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nethanel\WebstormProjects\untitled2\angular2-seed\npm-debug.log

**Comment by NathanielMalca** [comment] 2016-03-07 16:53
regarding #147 : npm  install -g ts-node ,npm run postinstall didn't help @mgechev

**Comment by d3viant0ne** [comment] 2016-03-07 16:54
The problem isn't with the seed, it's your nodejs environment.

**Comment by NathanielMalca** [comment] 2016-03-07 16:55
@d3viant0ne  can you see what's wrong?

**Comment by d3viant0ne** [comment] 2016-03-07 16:57
1.) gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
2.) npm ERR! Please try running this command again as root/Administrator.

**Comment by NathanielMalca** [comment] 2016-03-07 16:57
strange , it should be installed - checking

**Comment by d3viant0ne** [comment] 2016-03-07 17:03
Installed, maybe but definitely not on your PATH.

I'm not much of a Windows guy anymore and to be completely honest, Windows is the OS that NodeJS has the worst support for.

IMO - If I had to work on a PC, I would run an Ubuntu VM on top of it for NodeJS development and share a folder back to my repo folder on the host PC.

**Comment by d3viant0ne** [comment] 2016-03-07 17:05
You also have some sort of funky user / permissions thing happening.
Depending on if this is a domain joined / IT managed PC or just a personal, there could be issues.

Honestly, the best place to try and get help would be the NodeJS gitter chat.

**Comment by d3viant0ne** [comment] 2016-03-07 17:07
And just so you don't think i'm talking out my ass - http://recordit.co/qLcgg0AoBM

Latest master after "npm run reinstall"

**Comment by d3viant0ne** [comment] 2016-03-07 19:21
@NathanielMalca - I'm going to close this issue.

If you are still having issues, come find me in [Gitter](https://gitter.im/mgechev/angular2-seed) and I'll do what I can.

**Closed by d3viant0ne** 2016-03-07 19:21 UTC

**Comment by NathanielMalca** [comment] 2016-03-08 13:07
thanks, It appears that my Python environment variable got erased somehow.

That totally is not an issue for the seed but was instead a Nodejs issue.

Thanks  :)
