### ISSUE TITLE
Hot Loader

### ISSUE THREAD

**Issue by Bigous** [mgechev/angular2-seed#284] opened 2015-12-09 19:37 UTC
Hi @mgechev , it would be greate if we could have Hot Loader in development environment in this seed.

**Comment by mgechev** [comment] 2015-12-10 09:09
@Bigous thats a good idea! Next a couple of weeks I'll work on the hot loader in order to make it ready for usage and integrate it in the seed.

Initially it will be accessible through an experimental flag.

**Comment by Bigous** [comment] 2015-12-10 17:37
@mgechev Awesome!!!

**Comment by mgechev** [comment] 2015-12-12 18:16
Getting closer https://www.npmjs.com/package/angular2-hot-loader
Only integration behind an experimental flag with the seed is left.

**Comment by NathanWalker** [comment] 2015-12-12 19:09
Very exciting!

**Comment by Bigous** [comment] 2015-12-13 12:09
\o/ uhuuu!

**Comment by mgechev** [comment] 2015-12-15 15:29
The experimental hot loading support is in the [hot-loader branch](https://github.com/mgechev/angular2-seed/tree/hot-loader).

**Comment by Bigous** [comment] 2015-12-15 17:34
Hi @mgechev excelent news.
I've merged my seed with the hot-loader branch, npm install (and run reinstall cleaning cache, etc...) it always fails when I try ```npm start -- --hot-loader true```.
This is my shell error:
```shell
>> nothing rebundled
[14:22:18] Requiring external module ts-node/register
Error: Cannot find module 'angular2-hot-loader'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\src\GitHub\Bigous\Ng2Highcharts\tools\utils\code_change_tools.ts:4:25)
    at Module._compile (module.js:435:26)
    at Object.loader (D:\src\GitHub\Bigous\Ng2Highcharts\node_modules\ts-node\dist\ts-node.js:121:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Dev\\nodejs\\node.exe" "D:\\Dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.3
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 postinstall: `tsd reinstall --clean && tsd link && tsd rebundle && gulp check.versions
&& gulp postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 postinstall script 'tsd reinstall --clean && tsd link && tsd rebundle &&
gulp check.versions && gulp postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsd reinstall --clean && tsd link && tsd rebundle && gulp check.versions && gulp postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\src\GitHub\Bigous\Ng2Highcharts\npm-debug.log
```
But the node module ```angular2-hot-loader``` is correctly installed under ```node_modules```.
My environment is ```Win10 x64``` - ```node 4.2.3``` and ```npm 3.3.10```.

**Comment by mgechev** [comment] 2015-12-15 20:18
@Bigous would you give it a try again? I didn't publish the module properly.

**Comment by Bigous** [comment] 2015-12-16 12:29
Hi @mgechev, Now it starts normally, but gives me the following error when I update a component (about.ts for example):
```console
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
Clicked link
Error: Module angular2/common not declared as a dependency.(…)
  ws.onmessage @ ng2-hot-loader.js:216
  run                    @ angular2-polyfills.js:138
  zoneBoundFn   @ angular2-polyfills.js:111
```
And when a template file is updated (like about.html) nothing happens...
Getting closer ;) and tks
[]s

**Comment by mgechev** [comment] 2015-12-16 12:56
@Bigous thanks for the feedback and the patience! The issue you reported is temporary fixed now, however I'd need to come up with a better solution in near future.

I can't reproduce the one which occurs when you change the templates, for me when any of the templates change everything reflects in the browser.

**Comment by Bigous** [comment] 2015-12-16 13:29
@mgechev Working as expected. Congratulation!!!! :+1: :smiley: 
The HTML template do not update anything yet, but I can live with it... just update the .TS file and the component is updated without full reload! Awesome!!!

**Comment by Bigous** [comment] 2015-12-16 13:43
@mgechev I see what you called "better solution", when the component imports another custom component, it still gives-me the error:
```console
Error: Module ../../directives/ng2-highcharts/ng2-highcharts not declared as a dependency.
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js:2990:13
    at require (http://localhost:5555/node_modules/systemjs/dist/system.src.js:3570:29)
    at eval (eval at processMessage (unknown source), <anonymous>:8:24)
    at eval (eval at processMessage (unknown source), <anonymous>:49:2)
    at processMessage (http://localhost:5578/ng2-hot-loader.js:200:9)
    at WebSocket.ws.onmessage [as _onmessage] (http://localhost:5578/ng2-hot-loader.js:215:17)
    at Zone.run (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
    at WebSocket.zoneBoundFn (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:111:19)
ws.onmessage @ ng2-hot-loader.js:218
run @ angular2-polyfills.js:138
zoneBoundFn @ angular2-polyfills.js:111
```
But, for components that uses angular core as dependency, it's working to me.

**Comment by mgechev** [comment] 2015-12-16 13:43
Thanks for trying it out!

Currently the only way to preserve the state is to keep it inside a service which you can later inject with the DI mechanism of Angular. I believe that this hot loader can work perfectly with something like [redux](https://github.com/wbuchwalter/ng2-redux). I'm not completely familiar with the implementation I referred to but I think its worth spending some time playing with it.

**Comment by sclausen** [comment] 2015-12-16 17:23
@mgechev wouldn't be the not so experimental lazy-loadign example from your blog another great gain for this project?

**Comment by mgechev** [comment] 2015-12-16 18:06
You mean 'AsyncRoute'? Yes, it could be.

**Comment by Bigous** [comment] 2015-12-16 19:52
Now, imagine the Hot Loader with the AsyncRoute... sounds the perfect world :smiley:

**Comment by sclausen** [comment] 2015-12-16 22:23
@mgechev not exactly the asyncroute, but your own loader you implemented

**Comment by Bigous** [comment] 2015-12-17 17:38
Hi @mgechev , With the last update made, it is failing when trying to processMessage :
```console
Error: Failed to construct 'URL': Invalid URL
	Error loading \app\components\home\home.ts
    at TypeError (native)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:1570:16)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:1826:32)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:2152:34)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:3538:24)
    at SystemJSLoader.normalizePlugin (http://localhost:5555/node_modules/systemjs/dist/system.src.js:4036:24)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:4043:30)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js:4320:26
    at Zone.run (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
    at zoneBoundFn (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:111:19)
(anonymous function) @ ng2-hot-loader.js:216
run @ angular2-polyfills.js:138
zoneBoundFn @ angular2-polyfills.js:111
run @ angular2-polyfills.js:138
zoneBoundFn @ angular2-polyfills.js:111
lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511
lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523
lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494
lib$es6$promise$$internal$$publishRejection @ angular2-polyfills.js:1444
(anonymous function) @ angular2-polyfills.js:243
run @ angular2-polyfills.js:138
zoneBoundFn @ angular2-polyfills.js:111
lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
```
I think it's sending the wrong url to download the updated component.
[]s

**Comment by mgechev** [comment] 2015-12-18 14:31
@Bigous it should be alright now.

**Comment by mgechev** [comment] 2015-12-22 06:47
@Bigous have you experienced any other issues with hot loader?

**Comment by Bigous** [comment] 2015-12-22 12:34
Hi @mgechev, sorry for the delay...
Still getting:
```console
Error: Failed to construct 'URL': Invalid URL
	Error loading /app/components/home/home.ts
    at TypeError (native)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:1570:16)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:1826:32)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:2152:34)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:3538:24)
    at SystemJSLoader.normalizePlugin (http://localhost:5555/node_modules/systemjs/dist/system.src.js:4036:24)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:4043:30)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js:4320:26
    at Zone.run (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
    at zoneBoundFn (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:111:19)
(anonymous function) @ ng2-hot-loader.js:217
```

**Comment by ludohenin** [comment] 2015-12-22 12:46
Same as @Bigous for me.

**Comment by mgechev** [comment] 2015-12-22 16:46
@Bigous @ludohenin what version of systemjs are you using?

**Comment by Bigous** [comment] 2015-12-23 19:14
Hi @mgechev, I deleted the ```node_modules```, run, ```npm install``` and ```npm start -- --hot-loader```(tryed ```npm start -- --hot-loader true``` too just in case), with same results...
```console
Error: Failed to construct 'URL': Invalid URL
	Error loading /app/components/home/home.ts
    at TypeError (native)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:1596:16)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:1860:32)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:2186:34)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:3572:24)
    at SystemJSLoader.normalizePlugin (http://localhost:5555/node_modules/systemjs/dist/system.src.js:4070:24)
    at SystemJSLoader.<anonymous> (http://localhost:5555/node_modules/systemjs/dist/system.src.js:4077:30)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js:4342:26
    at Zone.run (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
    at zoneBoundFn (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:111:19)
(anonymous function) @ ng2-hot-loader.js:217
run @ angular2-polyfills.js:138
zoneBoundFn @ angular2-polyfills.js:111
run @ angular2-polyfills.js:138
zoneBoundFn @ angular2-polyfills.js:111
lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511
lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523
lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494
lib$es6$promise$$internal$$publishRejection @ angular2-polyfills.js:1444
(anonymous function) @ angular2-polyfills.js:243
run @ angular2-polyfills.js:138
zoneBoundFn @ angular2-polyfills.js:111
lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
```

**Comment by mgechev** [comment] 2015-12-23 23:08
@Bigous with the latest changes this issue is fixed. However, currently when the root component is updated we loose the providers associated to it. If you move the `NameList` provider to the `hot_loader_bootstrap.ts` initialization you will make it work well and you'll be able to keep the state between updates.

**Comment by Bigous** [comment] 2015-12-28 13:49
Merry Christmas everyone!.
Cool, everything is working again @mgechev ! Tks.

**Closed** 2016-01-02 15:05 UTC
Labels: enhancement
