### ISSUE TITLE
protractor test fails with "Error: Server terminated early with status 1"

### ISSUE THREAD

**Issue by allenhwkim** [mgechev/angular2-seed#738] opened 2016-04-07 21:10 UTC
When I run command `protractor` I have the error above

First I ran 

`$ gulp serve.e2e`

Then, I ran

`$ protractor`

In result, I see the following error.
```
$ protractor
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver

C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329
      return callbackFn(this.value_);
             ^
Error: Server terminated early with status 1
    at Error (native)
    at C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\remote\index.js:210:20
    at Promise.invokeCallback_ (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
    at TaskQueue.execute_ (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    at TaskQueue.executeNext_ (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    at C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2652:27
    at C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at acquireSession (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:62:22)
    at Function.createSession (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:295:12)
    at Driver (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:778:38)
    at [object Object].DirectDriverProvider.getNewDriver (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\direct.js:69:16)
    at [object Object].Runner.createBrowser (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\built\runner.js:203:37)
    at C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\built\runner.js:293:21
    at _fulfilled (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
[launcher] Process exited with error code 1
```
I was expecting the test result instead of error

Additional Information
```
$ node --version
v5.10.1

$ npm -v
3.8.5
```

**Comment by TheDonDope** [comment] 2016-04-08 08:03
Hi allenhwkim,

take a look at the README.md. To run the e2e tests, you need to do the following:

```
# e2e (aka. end-to-end, integration) - In three different shell windows
# Make sure you don't have a global instance of Protractor

# npm run webdriver-update <- You will need to run this the first time
npm run webdriver-start
npm run serve.e2e
npm run e2e

# e2e live mode - Protractor interactive mode
# Instead of last command above, you can use:
npm run e2e.live
```

So, to start the e2e test you need to run `$ npm run e2e` and not `protractor`. Also make sure you started the webdriver.

Greetings

**Comment by allenhwkim** [comment] 2016-04-08 22:42
This is only happening on windows environment. 
I ran on Mac and it works fine.

**Comment by mgechev** [comment] 2016-04-09 08:57
Can you reproduce the issue following the instructions in the readme?

**Comment by allenhwkim** [comment] 2016-04-09 14:38
@mgechev Yes in windows 10. It could be my environmental issue. To make it sure it's my environmental issue, I need to test it with other machine.

**Comment by mgechev** [comment] 2016-04-09 15:04
@allenhwkim we're interested in supporting windows since it is a major platform used for development. Unfortunately I wasn't able to reproduce your issue on my Windows 10 VM running in Parallels:

![](https://s29.postimg.org/9swueb0hj/Screen_Shot_2016_04_09_at_18_02_31.png)

**Comment by mgechev** [comment] 2016-04-18 08:39
Since there are no updates here, I'll close the issue for now and keep an eye on it if there's something new.

**Closed by mgechev** 2016-04-18 08:39 UTC
