### ISSUE TITLE
Tsd reinstall often fails with 'Github rate exceeded'

### ISSUE THREAD

**Issue by jesperronn** [mgechev/angular2-seed#176] opened 2015-10-20 21:13 UTC
This build, for instance: https://travis-ci.org/mgechev/angular2-seed/jobs/86486664#L156

Fails with

```
tsd reinstall --clean && tsd link && tsd rebundle && gulp postinstall -> running reinstall
    [ERR!] GitHub API: GitHub rate limit reached.
    To increase the limit use GitHub authentication.
    See: https://github.com/DefinitelyTyped/tsd#tsdrc
```

Documentation itself suggests to add a `token` into `.tsdrc`. Which is kind-of weird to have on Travis/CircleCI since it's a private github key.

Imagine if npm dependencies were pulled from Github. A CI provider would easily spend the 60 api requests per hour. Forgive my lack of knowledge, but why is tsd pulling this from Github and precicely what is it pulling from Github?

Is there a way that stuff inside the `tsd` command can be cached? Or pulled from somewhere else?

**Comment by tarlepp** [comment] 2015-10-21 15:04
This can be solved simply by create of auth token for tsd. This is described in https://github.com/DefinitelyTyped/tsd#tsdrc

\\CC @mgechev You should create this token as described and then create ENV variable to Travis configuration.

**Comment by jesperronn** [comment] 2015-10-21 15:08
I understand. But I have the impression that these tokens are personal and
therefore should not be committed into repository. Is this correct?

For instance if I create a token with my github account, then this token
can be used to make other API requests on my behalf. I should never submit
that into this repository (even thought I was pretty close doing that).

Is this correctly understood?

Also, if you have links explaining extactly what `tsd` is doing and why it
needs to access github at this point??? I don't understand, and assume it
must slow the build down.


On Wed, Oct 21, 2015 at 5:04 PM, Tarmo Leppänen <notifications@github.com>
wrote:

> This can be solved simply by create of auth token for tsd. This is
> described in https://github.com/DefinitelyTyped/tsd#tsdrc
>
> \CC @mgechev <https://github.com/mgechev> You should create this token as
> described and then create ENV variable to Travis configuration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgechev/angular2-seed/issues/176#issuecomment-149925312>
> .
>



-- 

Jesper Rønn-Jensen
Nine A/S
Mobile: +45 2989 1822
Blog http://justaddwater.dk/
jesperrr@gmail.com (Private e-mail and Google Talk IM)

**Comment by tarlepp** [comment] 2015-10-21 15:12
The problem is within Travis CI integration, which is triggered to run whenever someone makes new PR to this repo.

So the fix is just to add environment variable ```TSD_GITHUB_TOKEN``` to Travis CI settings and all is fixed. I can't do that, because @mgechev is the "owner" of Travis CI integration.

**Comment by jesperronn** [comment] 2015-10-21 15:21
Forgive my ignorance...

But updating tsd files should probably lie in the hands of the developers
submitting the pull-requests.

Is there a way to avoid having tsd making calls when building?? Wouldn't it
be better to fail the build on Travis if there is some sort of mismatch
between the tsd files and the .ts files??

What advantage does it have to make the tsd api calls?


On Wed, Oct 21, 2015 at 5:12 PM, Tarmo Leppänen <notifications@github.com>
wrote:

> The problem is within Travis CI integration, which is triggered to run
> whenever someone makes new PR to this repo.
>
> So the fix is just to add environment variable TSD_GITHUB_TOKEN to Travis
> CI settings and all is fixed. I can't do that, because @mgechev
> <https://github.com/mgechev> is the "owner" of Travis CI integration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgechev/angular2-seed/issues/176#issuecomment-149927715>
> .
>



-- 

Jesper Rønn-Jensen
Nine A/S
Mobile: +45 2989 1822
Blog http://justaddwater.dk/
jesperrr@gmail.com (Private e-mail and Google Talk IM)

**Comment by tarlepp** [comment] 2015-10-21 15:30
See #171 for more information.

**Comment by jesperronn** [comment] 2015-10-21 15:34
Point taken. So with #171, we ignore tsd files, since compiler must download ts-definitions for js libraries when they should be used. Then, for me, makes sense, then to follow @tarlepp suggestion to add `TSD_GITHUB_TOKEN`.

Thanks for explaining @tarlepp  :+1:

**Comment by tarlepp** [comment] 2015-10-21 15:37
np

**Comment by jesperronn** [comment] 2015-10-21 15:47
Oh, one more thing https://github.com/DefinitelyTyped/tsd/#notes notes that 

> It is recommended you check-in the definitions you install into your VCS.

Shouldn't we do that instead (as a separate task locally)?? This again means no CI build will get the rate error. 

Why would DefinitelyTyped prefer that opposed to the strategy to reinstall??

**Comment by mgechev** [comment] 2015-10-23 06:12
I was busy with AngularConnect last week. I will take a look at this issue during the weekend.

**Comment by sclausen** [comment] 2015-10-31 13:35
@jesperronn The official recommendation to check-in the local installed definitions is imho a really dirty hack with nasty sideeffects like bloating the repo and will probably result in huge diffs, when any tsd-definition version changes. I think the approach of @tarlepp would be the best solution to solve this problem without missing CI.

**Comment by tarlepp** [comment] 2015-10-31 22:54
Actually that ENV variable is allready set to this repo by @ludohenin so that should not be a problem anymore. Although I think that it is good to mention this in README.md and guide user to create ```.tdsrc``` file and attach their own token there.

**Comment by mgechev** [comment] 2015-11-01 13:04
@ludohenin lets close this one.

**Closed by mgechev** 2015-11-01 13:04 UTC
