### ISSUE TITLE
Getting error after generate new Component

### ISSUE THREAD

**Issue by arifhussain353** [mgechev/angular2-seed#1411] opened 2016-09-30 15:19 UTC
Hi,
I create new component by following `HomeComponent` and add require reference to all file where `HomeComponent` exist.New component named `login`.After `npm start` i got this error.I am new on angular seed.How can i create new component ?.Did i miss any reference to be add ?.I don't have any duplicate directory of LOGIN.

......
[20:08:07] 'build.assets.dev' errored after 341 ms
[20:08:07] Error: EEXIST: file already exists, mkdir 'D:\xampp\xampp\htdocs\angular2-seed\dist\dev\app\login'
    at Error (native)
[20:08:07] 'serve.dev' errored after 361 ms
[20:08:07] Error in plugin 'run-sequence(build.assets.dev)'
Message:
    EEXIST: file already exists, mkdir 'D:\xampp\xampp\htdocs\angular2-seed\dist\dev\app\login'
Details:
    errno: -4075
    code: EEXIST
    syscall: mkdir
    path: D:\xampp\xampp\htdocs\angular2-seed\dist\dev\app\login
Stack:
Error: EEXIST: file already exists, mkdir 'D:\xampp\xampp\htdocs\angular2-seed\dist\dev\app\login'
    at Error (native)
[20:08:07] 'build.dev' errored after 348 ms
[20:08:07] Error in plugin 'run-sequence(serve.dev)'
Message:
    EEXIST: file already exists, mkdir 'D:\xampp\xampp\htdocs\angular2-seed\dist\dev\app\login'
Details:
    errno: -4075
    code: EEXIST
    syscall: mkdir
    path: D:\xampp\xampp\htdocs\angular2-seed\dist\dev\app\login
Stack:
Error: EEXIST: file already exists, mkdir 'D:\xampp\xampp\htdocs\angular2-seed\dist\dev\app\login'
    at Error (native)
[20:08:07] 'build.dev' errored after 349 ms
[20:08:07] Error in plugin 'run-sequence(build.assets.dev)'
Message:
    EEXIST: file already exists, mkdir 'D:\xampp\xampp\htdocs\angular2-seed\dist\dev\app\login'
Details:
    errno: -4075
    code: EEXIST
    syscall: mkdir
    path: D:\xampp\xampp\htdocs\angular2-seed\dist\dev\app\login
Stack:
Error: EEXIST: file already exists, mkdir 'D:\xampp\xampp\htdocs\angular2-seed\dist\dev\app\login'
    at Error (native)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\xampp\xampp\htdocs\angular2-seed\npm-debug.log

**Comment by arifhussain353** [comment] 2016-09-30 15:38
issue is solved by rename `login` folder to `login1`.But why ?. I don't have any login folder duplicated

**Comment by mgechev** [comment] 2016-09-30 17:44
I can't reproduce the issue. Most likely the problem is not related to the directory name but to a race condition somewhere which might or might not be related to the seed project.

Lets close the issue for now and review it again if someone reports a similar problem.

**Closed by mgechev** 2016-09-30 17:44 UTC
