### ISSUE TITLE
build.js.test.ts should use APP_DEST for inlineNg2Template

### ISSUE THREAD

**Issue by sunyuhang** [mgechev/angular2-seed#530] opened 2016-02-23 15:58 UTC
when using 'jade,  APP_SRC only has jade files. APP_DEST has the html files transpiler from those jade files.

So, line 17 could be the following instead

```
.pipe(plugins.inlineNg2Template({ base: APP_DEST, useRelativePaths: true }))
```

However, the proposed change is not working. I am not sure why.

Thanks,
Yuhang

**Comment by mgechev** [comment] 2016-02-25 13:26
@ludohenin would you take a look at this one? I think using `templatePreprocessor` may solve this problem.

Closing it since it is not related to the seed because we do not officially support jade. The issue is matter of a way to extending the seed.

@sunyuhang @ludohenin it'll be great to add a wiki page for `jade` support once you solve it!

**Closed by mgechev** 2016-02-25 13:26 UTC

**Comment by ludohenin** [comment] 2016-02-25 13:32
Yes, for me the way to go is to use `templateProcessor` function of gulp-inline-ng2-template.
[here](https://github.com/ludohenin/gulp-inline-ng2-template/blob/master/test/test.js#L70-L72) is a simple implementation.
