### ISSUE TITLE
Broken project compilation on change

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#318] opened 2015-12-21 20:16 UTC
With this revision 845772264ef64ad5fcc1a33293d714962ced9a63 when I save my changes project is not rebuilt automatically and I need to stop npm process and restart it again in my terminal to rebuild it.

**Comment by mgechev** [comment] 2015-12-22 06:43
Thanks for reporting the issue! The issue is fixed by https://github.com/mgechev/angular2-seed/commit/8fd110f4b825839af7e5ced634d69fe7f8973bf9

**Closed by mgechev** 2015-12-22 06:43 UTC
