### ISSUE TITLE
Cannot run: npm run build.prod

### ISSUE THREAD

**Issue by AntonFLB** [mgechev/angular2-seed#1227] opened 2016-08-18 08:54 UTC
**Steps to reproduce and a minimal demo of the problem**
Just start the npm run build.prod after npm install

**Current behavior**
see attached log file

**Expected/desired behavior**
build all files

[npm-debug.txt](https://github.com/mgechev/angular2-seed/files/424469/npm-debug.txt)

Any idea whats going wrong?

Thanks for help
Anton

**Comment by Bigous** [comment] 2016-08-23 17:43
Couldn't reproduce
commit bc2a4890b47ad1f808ad45f0904b802ef439afe5
npm 3.10.3
node v6.4.0
Windows 10

**Comment by gaurang171** [comment] 2016-09-15 13:34
I have the similar Issue on 
Windows 10 64bits, node 4.5.0

build.prod is failing at    
> build.bundles.app

Instead of finding dist/tmp folder in root. it build try to find in under node_modules.
Should be some minor config change but not able to figure out due to my very limited knowledge of gulp. 


```
[09:12:17] 'build.bundles.app' errored after 2.56 s
[09:12:17] Error on fetch for dist\tmp\app\main.js at file:///C:/REPOS/angular2-seed/node_modules/dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'C:\REPOS\angular2-seed\node_modules\dist\tmp\app\main.js'
    at Error (native)
[09:12:17] 'build.prod' errored after 55 s
[09:12:17] Error in plugin 'run-sequence(build.bundles.app)'

Message:
    Error on fetch for dist\tmp\app\main.js at file:///C:/REPOS/angular2-seed/node_modules/dist\tmp\app\main.js
        ENOENT: no such file or directory, open 'C:\REPOS\angular2-seed\node_modules\dist\tmp\app\main.js'

Details:
    originalErr: Error: ENOENT: no such file or directory, open 'C:\REPOS\angular2-seed\node_modules\dist\tmp\app\main.js'


Stack:
Error on fetch for dist\tmp\app\main.js at file:///C:/REPOS/angular2-seed/node_modules/dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'C:\REPOS\angular2-seed\node_modules\dist\tmp\app\main.js'
    at Error (native)
```

I hope this helps.

**Comment by Zaljin** [comment] 2016-09-20 13:33
@gaurang171 
I am encountering the same issue with prod.build

@Bigous 
This is a different issue from OP.

**Comment by 799956381** [comment] 2016-09-20 14:05
@Zaljin @gaurang171 
I am encountering the same issue with prod.build.
I hope this helps.

**Comment by gaurang171** [comment] 2016-09-20 20:32
found the solution its systemjs-builder's issue with windows. 

needed to add windows specific paths to system builder. 

```
  Config.SYSTEM_BUILDER_CONFIG.paths = { 
  'dist\\tmp\\app\\*': 'dist/tmp/app/*', 
  'dist/tmp/*': 'dist/tmp/*',
  'dist\\tmp\\*': 'dist/tmp/*',
  '*': 'node_modules/*'
}
```

here is the code change. of 
seed.config.ts  -> SYSTEM_BUILDER_CONFIG

```
paths: {
      [`${this.TMP_DIR}/app/*`.replace(/\//g, '\\')]: `${this.TMP_DIR}/app/*`,
      [`${this.TMP_DIR}/*`]: `${this.TMP_DIR}/*`,
      [`${this.TMP_DIR}/*`.replace(/\//g, '\\')]: `${this.TMP_DIR}/*`,
      '*': 'node_modules/*'
    },
```


Even if its windows related. i dont know why i needed to add tmp/app in the paths.  didnt test this on linux hopefully there you dont need tmp/app

**Comment by mgechev** [comment] 2016-09-20 22:05
@gaurang171 would you verify if you need this fix with the latest SystemJS builder?

**Comment by gaurang171** [comment] 2016-09-21 01:07
@mgechev 
giving same error for latest version 0.15.31.

**Comment by mgechev** [comment] 2016-09-21 01:12
According to https://github.com/systemjs/builder/issues/621, SystemJS builder normalizes paths. Given this, I am wondering what causes the issue.

**Comment by mgechev** [comment] 2016-09-26 18:37
Closing the issue since we already have a proposed solution by @gaurang171 and there are no updates.

**Closed by mgechev** 2016-09-26 18:37 UTC

**Comment by m-roosta** [comment] 2017-06-29 15:25
I have same error with lazy branch when run build.prod script

Error: Error on fetch for dist\tmp\app\home.component.js at file:///D:/Axineh/Source/Repos/Axineh/Axineh.WebApp/angular-seed-lazy/dist/tmp/app/home.component.js
	Loading dist\tmp\app\home\home.module.js
