### ISSUE TITLE
gulp-inject injecting full path

### ISSUE THREAD

**Issue by roded** [mgechev/angular2-seed#1194] opened 2016-08-05 16:56 UTC
Hi, 
Not sure if there is an actual problem, or this is due to my own ignorance. Either way, assistance would be much appreciated.
I followed the repository's instructions and the server runs fine with `npm start`.
However, it seems like the resources injection uses the full file paths, drive and all, i.e.; `http://localhost:5555/C:/.../angular2-seed/node_modules/systemjs/dist/system.src.js?1470416053302`
On Windows (obviously), node 6.3.1 npm 3.10.3.
Thanks

**Comment by mgechev** [comment] 2016-08-05 20:24
Is it a clean clone or you did changes in the config?

**Comment by roded** [comment] 2016-08-05 20:42
@mgechev clean clone.

**Comment by mgechev** [comment] 2016-08-14 00:14
Hey @roded, I just tried to reproduce the issue under Windows 10 with Node 6.3.1 but without any results. Would you test against the latest master and tell me if the problem still exists?

**Comment by webia1** [comment] 2016-08-15 08:45
I had similar problems on Windows (but not in MacOS), after I have added some new routes. 

There were basically 4 error error sources in my case:

1.  Differences between process.cwd() and __dirname
2.  Different behavior on Windows/Mac/Linux of e.g. `${this.APP_BASE}` in some cases, I had to remove it and use the root directory name ( I can't remember, in which case)
3.  Using join because of window/linux paths ( / vs \ )
4.  Adding a route for Browsersync

**Comment by roded** [comment] 2016-08-15 13:02
I suspect something is wrong with my own configuration. Though I cannot say what precisely.
Here's the full process{

Following the README.md, `npm install` fails with:
`[15:58:24] Requiring external module ts-node/register

C:\Roded\#downloads\angular2-seed\node_modules\ts-node\src\index.ts:259
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
Cannot find the common subdirectory path for the input files. (5009)
    at getOutput (C:\Roded\#downloads\angular2-seed\node_modules\ts-node\src\index.ts:259:17)
    at C:\Roded\#downloads\angular2-seed\node_modules\ts-node\src\index.ts:268:16
    at Object.compile (C:\Roded\#downloads\angular2-seed\node_modules\ts-node\src\index.ts:404:17)
    at loader (C:\Roded\#downloads\angular2-seed\node_modules\ts-node\src\index.ts:290:33)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Roded\#downloads\angular2-seed\node_modules\ts-node\src\index.ts:307:14)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)`

Thereafter, I can run `tsc --project tsconfig.json` at which point `npm start` exhibits the behaviour described above (full-path replacement).

Apologies if this is a local issue and out of the scope of angular2-seed. If so, I'll look for a solution elsewhere.

**Comment by mgechev** [comment] 2016-08-17 16:44
This seems like a different issue. I guess we can close this one.

**Comment by mgechev** [comment] 2016-08-17 16:45
What's your operating system and node version?

**Comment by roded** [comment] 2016-08-17 17:18
Windows 10, node v6.3.1 via nvm.

**Comment by mgechev** [comment] 2016-08-17 18:56
Oh, I wasn't following the discussion. Yes, I did try to reproduce the issue with the exact same environment but without any luck. Lets keep it open in case anyone else experience it, otherwise we can conclude that it's something related to your specific environment.

**Closed** 2016-08-23 18:19 UTC
