### ISSUE TITLE
Traceur throws "duplication module named rx"

### ISSUE THREAD

**Issue by akorchemniy** [mgechev/angular2-seed#16] opened 2015-06-08 14:03 UTC
I tried to get the latest running but got stuck on "Loading...". It appears Traceur doesn't like that both angular2.js and router.js have a System.register("rx"

**Comment by mgechev** [comment] 2015-06-08 14:05
Thanks! I'll take a look on this one.

**Comment by mgechev** [comment] 2015-06-08 14:10
I can't manage to reproduce it. Would you give me additional details? What tag and environment are you using? Also, are you following the instructions in the readme, or doing something custom?

**Comment by akorchemniy** [comment] 2015-06-08 15:07
Nothing custom. Just the basics instructions using latest commit (afc023f048).
Windows
node 0.12.2
npm 2.7.4
gulp cli 3.8.11
angular2@2.0.0-alpha.26 node_modules\angular2
+-- rtts_assert@2.0.0-alpha.26
+-- zone.js@0.5.0
+-- traceur@0.0.87 (commander@2.6.0, semver@2.3.2, rsvp@3.0.18, glob@4.3.5, source-map-support@0.2.10)
+-- rx@2.5.1
Chrome

**Comment by mgechev** [comment] 2015-06-08 18:27
Cleared the `npm` cache. Installed node v0.12.2, npm 2.74 and still can't reproduce it.

Let's keep the issue open in case anyone else have experienced this problem.

**Comment by jgolla** [comment] 2015-06-08 19:54
I saw the same problem, but it only happened the first time I ran serve.dev. I was using a Mac, node, 0.12.4 and Chrome.

**Comment by ludohenin** [comment] 2015-07-01 20:47
@jgolla @akorchemniy Do you still have the issue with the alpha.28 ?

**Comment by ludohenin** [comment] 2015-07-05 16:55
I came across the same issue and for me the reason is very clear, a wrong component template url made the SPA server to re-send `index.html`. So loading twice the app throws this error.

**Comment by mgechev** [comment] 2015-07-06 17:54
May be we can close this issue then?

**Closed** 2015-07-06 17:54 UTC
Labels: bug
