### ISSUE TITLE
Npm start works fines, watch => build.dev produce unexpected JS

### ISSUE THREAD

**Issue by apavillet** [mgechev/angular2-seed#854] opened 2016-05-11 13:25 UTC
Npm starts does build the project correctly, website is working fine.

`15:08:24] Using gulpfile ~/Documents/Dev/orange-s2a/gulpfile.ts
[15:08:25] Starting 'serve.dev'...
[15:08:25] Starting 'build.dev'...
[15:08:25] Starting 'build.sass.dev'...
[15:08:26] Finished 'build.sass.dev' after 1.14 s
[15:08:26] Starting 'build.assets.dev'...
[15:08:27] Finished 'build.assets.dev' after 1.51 s
[15:08:27] Starting 'build.html_css'...
[15:08:34] Finished 'build.html_css' after 6.86 s
[15:08:34] Starting 'build.js.dev'...
[15:08:44] Finished 'build.js.dev' after 10 s
[15:08:44] Starting 'build.index.dev'...
[15:08:44] gulp-inject 4 files into index.html.
[15:08:44] gulp-inject 4 files into index.html.
[15:08:44] gulp-inject 3 files into index.html.
[15:08:44] Finished 'build.index.dev' after 208 ms
[15:08:44] Finished 'build.dev' after 20 s
[15:08:44] Starting 'server.start'...
[15:08:45] Finished 'server.start' after 186 ms
[15:08:45] Starting 'watch.dev'...
[15:08:45] Finished 'watch.dev' after 757 ms
[15:08:45] Finished 'serve.dev' after 21 s
`
Saving any file triggers the watch process as expected 

`15:09:24] Starting 'build.dev'...
[15:09:24] Starting 'build.sass.dev'...
[15:09:25] Finished 'build.sass.dev' after 325 ms
[15:09:25] Starting 'build.assets.dev'...
[15:09:28] Finished 'build.assets.dev' after 3.71 s
[15:09:28] Starting 'build.html_css'...
[15:09:29] Finished 'build.html_css' after 605 ms
[15:09:29] Starting 'build.js.dev'...
[15:09:32] Finished 'build.js.dev' after 2.63 s
[15:09:32] Starting 'build.index.dev'...
[15:09:32] gulp-inject 4 files into index.html.
[15:09:32] gulp-inject 4 files into index.html.
[15:09:32] gulp-inject 3 files into index.html.
[15:09:32] Finished 'build.index.dev' after 48 ms
[15:09:32] Finished 'build.dev' after 7.32 s
`
The build.dev complete and seems fine, but some of the js files produced make no sense :

Below are extract from one file generated first with npm start ( imports are ok and required with correct path, they are also all there)
`var core_1 = require('@angular/core');
var ng2_translate_1 = require('ng2-translate/ng2-translate');
var router_deprecated_1 = require('@angular/router-deprecated');
var home_1 = require('../home/components/home');
var actualite_1 = require('../actualites/components/actualite');
var forum_1 = require('../forum/components/forum');
var forum_detail_1 = require('../forum/components/forum-detail');
var tutoriels_1 = require('../tutoriels/components/tutoriels');
var tutoriel_detail_1 = require('../tutoriels/components/tutoriel-detail');
var quizz_detail_1 = require('../tutoriels/quizz/components/quizz-detail');
var tutoriels_folder_1 = require('../tutoriels/components/tutoriels-folder');
var shop_1 = require('../shop/components/shop');
var nav_1 = require('./nav');
var menu_aside_1 = require('./menu/menu-aside');
var profile_1 = require('../profile/components/profile');
var _404_1 = require('./404');
var profile_public_1 = require('../profile/components/profile-public');
var up_1 = require('../../shared/components/up');
var actu_detail_1 = require('../actualites/components/actu-detail');`

The second one is the same file generated from build.dev after the watch is triggered, notice path are not correct and a lot of imports are missing  (eg : var actu_detail_1 = require('../actualites/components/actu-detail'); becomes var actu_detail_1 = require('../home/components/actu-detail'); which is a wrong path)

`var core_1 = require('angular2/core');
var ng2_translate_1 = require('ng2-translate/ng2-translate');
var router_1 = require('angular2/router');
var home_1 = require('../home/components/home');
var actu_detail_1 = require('../home/components/actu-detail');
var forum_1 = require('../forum/components/forum');
var forum_detail_1 = require('../forum/components/forum-detail');
var documents_1 = require('../documents/components/documents');
var tutoriels_1 = require('../tutoriels/components/tutoriels');
var commandes_1 = require('../commandes/components/commandes');
var nav_1 = require('./nav');
var menu_aside_1 = require('./menu/menu-aside');
var user_service_1 = require('../../login/models/user.service');
var navbar_service_1 = require('../services/navbar.service');`

I've been banging my head around this for hours now and I cannot figure out what is the difference between the npm start and the watch task

Thanks

**Comment by mgechev** [comment] 2016-05-11 13:39
I can't reproduce this issue. Are you using clean copy of the seed or you have some custom configuration?

**Comment by apavillet** [comment] 2016-05-11 14:01
Hello @mgechev it's not, I tried on a clean install which seems to work.

I'm using the seed and only the src/client part is different, which lead me to drop the issue here ( also as I said npm start works ok, only the watch part produces an unexpected result)

I know it's difficult to answer since you do have all the elements, I was only trying to see if anyone already had, and solved, this issue.

Thanks

**Comment by mgechev** [comment] 2016-05-11 14:10
Take a look at the config. May be you're still referencing to `angular2/*` packages somewhere. I'll close this issue since it is not related to the current state of the seed but we can continue the discussion here.

**Closed by mgechev** 2016-05-11 14:10 UTC

**Comment by apavillet** [comment] 2016-05-12 08:21
I am, it's still wierd since the npm start files have '@angular/core' as import but then the build.dev on watch imports 'angular2/core' ...

I still do no get why but I had a quesiton, the watch build is much faster than it used to be, could you tell me what changed ? And could I try to reverse it to see if it fixes the issue?

Thanks

**Comment by mgechev** [comment] 2016-05-12 08:47
The build is faster because of gulp-cached and we also stopped cleaning the dist directory.

**Comment by apavillet** [comment] 2016-05-12 10:15
Thanks, i managed to make it work somehow.

For your information, and if you're not aware of it,  it seems to me that gulp-typescript > 2.10.0 ( namely 2.12 and 2.13 ) throws errors on watch 

`Could not find input file /Users/homengo/Documents/Dev/orange-s2a/src/src/site/home/models/tuto.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information: 
sourceRoot = "/Users/homengo/Documents/Dev/orange-s2a/src/"
sources = ["src/site/home/models/tuto.ts"]
`

Notice how src appears two times, probably APP_ROOT being appended ( downgrading to 2.10 works )

Thanks for your help
