### ISSUE TITLE
project.config overrides don't always work

### ISSUE THREAD

**Issue by vip32** [mgechev/angular2-seed#979] opened 2016-06-09 15:45 UTC
when using the following project.config.ts the PORT override is not used. after using npm start the site is still being served on port 5555. however the overridden APP_TITLE works fine.
Other override like PROD_DEST also are ignored. Changing the values directly in seed.config.ts is gives the desired result and the changes are applied (start or build.prod tasks).

is this a bug or am i overlooking something?

```
export class ProjectConfig extends SeedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();
    this.APP_TITLE = 'Event|Feedback2';
    this.PORT = 1133;
```

**Comment by mgechev** [comment] 2016-06-09 15:55
Seems like duplicate of #823 which is solved by https://github.com/mgechev/angular2-seed/pull/968.

**Closed by mgechev** 2016-06-09 15:55 UTC
