### ISSUE TITLE
Workflow for feature forks

### ISSUE THREAD

**Issue by nareshbhatia** [mgechev/angular2-seed#506] opened 2016-02-17 13:29 UTC
I am about to create a fork which will be adding Sass and specific component frameworks. Looking for ideas/workflows which will allow me to keep in sync with mgechev/angular2-seed without undoing my feature specific changes.

**Comment by mgechev** [comment] 2016-02-17 15:42
@NathanWalker is doing something similar in his [angular2-seed-advanced](https://github.com/NathanWalker/angular2-seed-advanced).

**Comment by nareshbhatia** [comment] 2016-02-17 15:54
Agree, seems like a hard problem to solve with Git. I see that @NathanWalker's project is not a fork of angular2-seed, although he started with the angular2-seed as the base. Love to hear more about his approach.

**Comment by d3viant0ne** [comment] 2016-02-17 16:14
@nareshbhatia - There is also discussion around adding support for pre-processors to inlineNg2Template. Seems a reasonable way to allow people to use sass, scss, stylus & so on while simplifying maintenance of the core.

**Comment by nareshbhatia** [comment] 2016-02-17 16:43
Agree. I am banking on @ludohenin to provide that feature (see issue #447). However, I will still have to create a fork for other integrations and keep it in sync with mgechev/angular2-seed to preserve all the goodness :-).

**Comment by ludohenin** [comment] 2016-02-17 17:23
Regarding the seed update, for me best option would be to move the tools to an npm package (say `angular2-seed-tools`) which would be overridden by the project specific config and tasks. This way we can keep tagging the the seed as new ng2 releases come along and version the tools separately.

**Comment by d3viant0ne** [comment] 2016-02-17 17:26
Certainly appears to be the only real seamless way to keep developing the seed without stepping on peoples toes.

**Comment by NathanWalker** [comment] 2016-02-18 00:32
@ludohenin that's an excellent idea. 

@nareshbhatia Problem with `feature forks` is that it rolls all issues into the parent, which is a problem. You wouldn't want all issues with your feature fork going back and spamming the parent. Which is why I chose **not** to make it a fork. Best way I've found is to:
* download repo as a zip file
* setup remote origin as your own repo
* setup remote upstream as `angular2-seed`
* periodically merge upstream changes into your "fork"

This works alright but obviously creates conflicts and depending on how far you ventured off the parent, could be really bad. Just depends in your case how much you are planning on changing things.
Ideally, what @ludohenin mentioned would make this sort of thing ideal. :+1:

**Comment by nareshbhatia** [comment] 2016-02-18 05:08
@NathanWalker, hmm that's an interesting one - issues from the feature fork roll up to parent!!!! That's not very good. I like your workaround - will go with that.

@ludohenin, not sure if I understand your solution. Even if tools is separated out, wouldn't we run into the same issue? The master tools branch and the forked branch will have enough differences that merges will become difficult.

**Comment by hpinsley** [comment] 2016-02-18 05:18
@nathanwalker That's the approach I adopted with https://github.com/hpinsley/angular-mashup
 I've gone through the pain of merging  upstream goodness because I failed to keep up . Consequently I have now resolved to merge upstream changes much more frequently.

**Comment by NathanWalker** [comment] 2016-02-18 05:55
@hpinsley Love the mashup, great work. I think there is a way to merge upstream changes and ignore certain folders which may help; I've seen that discussed somewhere but haven't tried it.

**Comment by Bigous** [comment] 2016-02-18 16:33
I'm working with the same pattern that @NathanWalker told us (with much more work because we use svn here, but the problem is the same).
Works for us... not perfect thou

**Comment by nareshbhatia** [comment] 2016-02-19 12:51
While working on my Sass extension, I am beginning to understand @ludohenin's idea better. It is like releasing a set of gulp tasks that can be combined and sequenced in various ways to achieve the desired build process. In other words, the end user will simply have to customize their `gulpfile` and run the tasks we provide in different sequences.

So far, for my Sass extension I had to modify the following:

1. `build.assets.dev.ts` - to exclude *.scss
2. `build.assets.prod.ts` - to exclude *.scss
3. `build.html_css.prod.ts` - to run sass for prod build
4. Added a new task `process.scss.ts` to process scss for dev builds

I think the trick to a successful tools effort is to come up with a generic enough tool chain that does not require surgery of existing tasks to support a different build process, e.g. what I have done in 1, 2 and 3 above. Perhaps we need to think of options that we can supply to these tasks so that they become more general purpose.

**Comment by ludohenin** [comment] 2016-02-19 12:56
@nareshbhatia I have preprocessors ready for the inlining plugin ... it doesn't work with sass. Could you have a look ?

**Comment by nareshbhatia** [comment] 2016-02-19 12:58
@ludohenin, next thing on my list :-)

**Comment by NathanWalker** [comment] 2016-02-21 01:31
I found a pretty good workflow that you could try for your `feature forks`.
Use this tool:
https://github.com/MestreLion/git-tools#git-strip-merge

Follow install instructions here:
https://github.com/MestreLion/git-tools#install

Then you can use a command similar to the following which will *ignore* everything in the `src` directory when merging upstream into your feature repo. You can specify anything you'd like to ignore there.
```
git-strip-merge upstream/master src/*
```

:+1:

**Comment by d3viant0ne** [comment] 2016-02-21 02:11
@NathanWalker Nice, i'll try that

**Comment by mgechev** [comment] 2016-02-25 12:58
It seems like the discussion in https://github.com/mgechev/angular2-seed/issues/506 is the same. In the meantime @ludohenin is solving the problem here https://github.com/mgechev/angular2-seed/pull/528.

Lets close this issue and keep the discussion https://github.com/mgechev/angular2-seed/issues/506.

**Comment by mgechev** [comment] 2016-02-25 13:19
Here's what I'm thinking about while reading the discussions here, https://github.com/mgechev/angular2-seed/issues/531 and https://github.com/mgechev/angular2-seed/pull/528.

## Problem

Using the seed as npm dependency is not that great choice as we already discussed. If we bet on this means that:
- We need to agree on a high-level API.
- Keep the API consistent, and go through a deprecation process.

In the end we'll have something like an abstraction over gulp, which doesn't seem necessary.

On the other hand, in case we decide to use the seed the way we use it now:
- Developers need to go through the manual process of cloning the seed.
- It is not obvious how to upgrade the seed.

The only benefit we get is that eventually developers can upgrade the seed using a gulp task, which delegates the call to node-git or something similar.

## Proposal

Build a very simple CLI tool with the following initial set of features:
- Bootstrap a new project - basically it will just **clone** the seed project.
- Update the seed - we will pull from master or any other branch we agree on.

The initial version of this tool will be less than 100 lines of code, however, it will have the following benefits:
- It'll be global npm module with very simple API. Developers will be able to use it like that:
  ``bash
  npm install -g ng2seed
  # Clone the seed in a directory called foobar
  ng2seed init foobar
  # Update seed
  ng2seed update
  ```
- It is going to provide a simple abstraction so developers don't have to know they are using this specific seed project
- We will be able to change the seed independency from the CLI tool (i.e. introduce new features, enhance it), so developers won't have to update their NPM packages.
- We get all the benefits from the change that @ludohenin will introduce here https://github.com/mgechev/angular2-seed/pull/528
- We can extend it with features like scaffolding - generation of directives, services, modules, pipes, tests, whatever.

## Pitfalls

- We will introduce yet another tool to learn.
- We still need to keep tasks with the same interface which seems almost trivial.

What are your thoughts on this?

**Comment by ludohenin** [comment] 2016-02-25 13:29
:100:

**Comment by ludohenin** [comment] 2016-02-25 16:19
To make even more simple and easier to maintain, why not just having the `ng2seed init` function and have all other `cli` features within the seed (in the form of tasks). The cli tool will then act as a proxy towards the seed.

### Pros
* Very limited update frequency of this project (`angular2-seed-cli`) as features will ships with the seed (in the form of tasks?)
* Single documentation location (the seed)
* CLI tools is optional and not a requirement

### Cons
* Will only work with this seed
* We loose independency from the CLI tool

**Comment by mgechev** [comment] 2016-02-25 16:25
@ludohenin yes, that is what I meant as well. The first pros brings great flexibility.

**Comment by fourctv** [comment] 2016-02-25 19:52
+1, great idea.

ng2seed init, would basically do:
- git clone seed
- npm install
- npm run test

All else could then be added as tasks, as suggested.

Simple,easy and gets the job done.

**Comment by mgechev** [comment] 2016-03-02 08:30
All these ideas are on progress in this PR https://github.com/mgechev/angular2-seed/pull/528.

Lets close this issue for now.

**Closed by mgechev** 2016-03-02 08:30 UTC
Labels: discuss
