### ISSUE TITLE
SystemJS configuration for modules utlizing package.json (specifically angular2-moment)

### ISSUE THREAD

**Issue by cviccaro** [mgechev/angular2-seed#615] opened 2016-03-10 20:30 UTC
Hi there, just as a preface, love the work you all have put into this.  I encountered a small issue when trying to import one specific npm module, but I'm not sure if this issue is germane to angular2-seed or not.  So I hope someone can clear it up.

The module angular2-moment is the only module I've used yet that wasn't working simply by installing via npm and importing into a .ts file.  I am a bit out of my depth here, but it seems like this module requires its package.json to be read in order to work with angular2-seed.  Without the configuration change below, a 404 is returned for /node_modules/moment.js (whereas it should be pulling /node_modules/moment/moment.js). In case this is a common thing, there is a small fix to add to the SystemJS configuration to get it to work.  

In tools/config/seed.config.ts, line 87, the packageConfigPaths key must be added to the options:

```
  protected SYSTEM_CONFIG_DEV = {
    defaultJSExtensions: true,
// ADD THIS LINE
    packageConfigPaths: [`${this.APP_BASE}node_modules/*/package.json`],
//
    paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      'angular2/*': `${this.APP_BASE}angular2/*`,
      'rxjs/*': `${this.APP_BASE}rxjs/*`,
      '*': `${this.APP_BASE}node_modules/*`
    },
    packages: {
      angular2: { defaultExtension: false },
      rxjs: { defaultExtension: false }
    }
  };
```

I've also posted this to angular2-moment (see https://github.com/urish/angular2-moment/issues/19)  If this is not relevant to angular2-seed, apologies!

**Comment by mgechev** [comment] 2016-03-11 13:04
@cviccaro thanks for the catch :-)

**Comment by andvasp** [comment] 2016-04-22 12:14
Hi Guys,

For material2 packages, the error shown below happens because of this line added when I insert the packages of material in System.config. After remove this line, it runs without problem. This problem is related on topic https://groups.google.com/forum/#!topic/angular-material2/7mBDJ6Mc9Lo

Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/@angular2-material/package.json(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"

**Comment by mgechev** [comment] 2016-04-22 12:27
Hi @andvasp when I find some time I'll provide a sample integration with material2.

Probably we should discuss to include it by default.

// cc @ludohenin @d3viant0ne

**Comment by ludohenin** [comment] 2016-04-22 16:38
@mgechev Sound like a good idea to me.

**Comment by d3viant0ne** [comment] 2016-04-22 16:50
@mgechev I've integrated the seed with Material2 already and continue to update it with each new release.

It's definitely not in a state yet where I would suggest integrating it into the seed proper. That said, when I think it's in a happy enough place, I can PR that in under an hour.

Right now it would be far more trouble than it's worth.

**Comment by mgechev** [comment] 2016-04-22 16:56
Sounds good to me :-)

**Comment by d3viant0ne** [comment] 2016-04-22 18:01
I suppose there is a caveat there. I haven't updated it to alpha3 yet, which I will be doing this evening after I get the seed running in a docker container using the new docker beta ( which is the hottness ) as it gets rid of VirtualSuck(box)

**Comment by andvasp** [comment] 2016-04-23 00:43
Hi guys.

@mgechev would be interesting to have material design included as default but I agree with @d3viant0ne. I believe is too early to include it.

I would like to emphasize the use of packageConfigPaths property in System.Config. Including it generated a problem to load the material design libraries when they are load from the packages in System.Config. Since material design is going to be used a lot, it is interesting to discuss the use of this property in the angular2 seed. I dont really know the effects to remove it in the seed. 

@d3viant0ne consider to use the material design libraries including them on system.Config as suggested by material design readme instead of include them in additional_deps. This way you avoid the error reported in the issue  https://github.com/DeviantJS/angular2-seed-material2/issues/10. I included in this issue some comments how to solve the problem. Please check it.

Thanks!

**Comment by d3viant0ne** [comment] 2016-04-24 21:04
@andvasp - Fork updated to alpha.3 & I added my take to the whole project.confg thing in DeviantJS/angular2-seed-material2#10

**Comment by nareshbhatia** [comment] 2016-04-30 21:15
Wish I had known about this thread before. I spent almost a day trying to integrate angular-material2 with angular2-seed! I finally arrived at the same workaround, i.e. remove `packageConfigPaths` from SystemJS configuration (you can find my repo [here](https://github.com/archfirst/angular2-seed-material)). In any case, what is `packageConfigPaths`? I didn't see it documented in SystemJS docs. What are we using it for in angular2-seed?

**Comment by nareshbhatia** [comment] 2016-04-30 22:02
Moreover, it appears that the issue is not with angular-material2. It has something to do with `packageConfigPaths`. I was able to start with angular2-seed alone and reduce it down to a minimal app and was able to reproduce the issue. Once I took out `packageConfigPaths` from SystemJS configuration the issue went away! Try it with this repo: https://github.com/archfirst/angular2-minimal-app - it should work with the code that is checked in. Now uncomment `packageConfigPaths` and `paths` in `index.html`. You will see that SystemJS starts requesting `package.json` files from the server and the application hangs!

**Comment by d3viant0ne** [comment] 2016-04-30 23:56
//cc @mgechev @ludohenin - Reopening this as @nareshbhatia is correct, this issue is reproducible in seed#master without the addition of other 3rd party libraries.

**Comment by njs50** [comment] 2016-05-02 18:45
packageConfigPaths is required if the node module doesn't just have all the files dumped in the root folder. Doesn't seem unreasonable to me. Does adding main or typings to the package.json in angular material then fix it?

seems like a problem with systemJs, in that as soon as you add that config it seems to expects every package.json to have main/typings defined (or maybe it's just main?).

**Comment by nareshbhatia** [comment] 2016-05-02 19:10
Where is `packageConfigPaths` documented? I couldn't find it anywhere.

**Comment by ludohenin** [comment] 2016-05-03 06:53
@nareshbhatia I found this https://github.com/systemjs/systemjs/blob/4bbfdcf8da782534b5e8236d75e53a8730d4a49d/lib/package.js#L60-L87

**Comment by nareshbhatia** [comment] 2016-05-03 07:33
Wow! You really dug deep to get to this. Thank you!

**Comment by ludohenin** [comment] 2016-05-03 07:54
@njs50 it doesn't look for `main` specifically but the whole supported options for `packages` as documented here https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages.

**Comment by marcusreese** [comment] 2016-05-03 14:01
>  +    packageConfigPaths: [`${this.APP_BASE}node_modules/*/package.json`],

This packageConfigPaths line also makes it hard to install @ngrx/store because the package.json is not in @ngrx/ but in @ngrx/store/, as discussed in the [commit](https://github.com/mgechev/angular2-seed/commit/6a011e955facf5ce50c35af2655c3756a3a5ace1).

**Comment by njs50** [comment] 2016-05-03 16:52
from the systemjs comments it looks like ``` * To opt-out of the package configuration request for a package that matches
 * packageConfigPaths, use the { configured: true } package config option.```

maybe that is how you are supposed to deal with problems caused by packageConfigPaths?

**Comment by mgechev** [comment] 2016-05-08 02:29
@nareshbhatia I can't reproduce the issue with SystemJS 0.19.27, can you still reproduce it?

**Comment by mgechev** [comment] 2016-05-08 02:36
Actually, I can't reproduce it with 0.19.25 neither.

**Comment by nareshbhatia** [comment] 2016-05-08 03:45
Can I understand how you are trying to reproduce it? As I mentioned earlier, I was not able to reproduce it with the full angular2-seed build. The only way I could do it was to reduce the build down to bare bones. Here's the repo for it: [angular2-minimal-app](https://github.com/archfirst/angular2-minimal-app) and here are the steps to reproduce it:

First make sure that the default build works correctly (detailed instructions in README.md):

```
npm install -g browser-sync
npm install -g lite-server
npm install -g ts-node
npm install
npm run build
npm start
```
Now edit `index.html` and uncomment `packageConfigPaths` and `paths`. Rebuild and run the application:

```
npm install
npm run build
npm start
```

You will see the following error in the console:

```
Failed to load resource: the server responded with a status of 404 (Not Found):
http://localhost:3000/node_modules/ponyfill/package.json
```

At this point SystemJS is completely confused and asking for non-sense stuff. Sorry, but I was never able to reproduce this with a full build of angular2-seed.

**Comment by andvasp** [comment] 2016-05-10 02:55
Hi Guys,

To include the angular-material2 in the seed project I just added the line below in the packageConfigPaths. Do you intend to have an options to include it in the file project.config.ts, the file that should be customized by the user? Maybe there are another cases for others components.

    packageConfigPaths: [  ...
      `${this.APP_BASE}node_modules/@angular2-material/*/package.json` ],

**Comment by vip32** [comment] 2016-05-20 11:19
you can add the material paths in project.config.ts like this:

```
this.SYSTEM_CONFIG_DEV.packageConfigPaths =
        this.SYSTEM_CONFIG_DEV.packageConfigPaths.concat([
          `${this.APP_BASE}node_modules/@angular2-material/*/package.json`
        ]);

**Comment by gtame** [comment] 2016-05-27 23:38
@vip32  Works!!! :+1:

**Closed** 2016-05-29 11:20 UTC
Labels: needs investigation
