### ISSUE TITLE
Browser reload fails after any code change

### ISSUE THREAD

**Issue by ShurikAg** [mgechev/angular2-seed#946] opened 2016-05-31 08:38 UTC
running `npm start` starts the application properly.

However, if I change any code, and npm tries to reload the browser I am getting the following error:

> (index):94 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/app/main.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"

stopping everything and restarting helps until the next code change.

This: https://github.com/mgechev/angular2-seed/wiki/Known-Issues does not help as well.

**Comment by mgechev** [comment] 2016-05-31 09:15
I can't reproduce the issue. If the code that you've entered is syntactically invalid TypeScript might have failed to parse it and respectively produce `main.js`.

**Comment by NathanielMalca** [comment] 2016-05-31 13:19
+1

**Comment by ShurikAg** [comment] 2016-05-31 16:16
@mgechev If it was syntactically invalid then it would fail on `npm start` as well, right? But it compiles without even warnings.

**Comment by ShurikAg** [comment] 2016-06-01 07:04
Maybe this is the problem...
http://prntscr.com/bawl3x
What does this mean exactly?

**Comment by mgechev** [comment] 2016-06-01 07:39
You said that it works initially (i.e. `npm start` works), and after a change fails (i.e. you might have introduced a syntax error).

Would you provide the output of:

```bash
$ tree dist/
```

**Comment by ShurikAg** [comment] 2016-06-01 07:41
`dist/
└── tmp
    ├── app
    │   ├── +about
    │   │   └── about.component.html
    │   ├── +home
    │   │   └── home.component.html
    │   ├── app.component.html
    │   └── shared
    │       ├── navbar
    │       │   └── navbar.component.html
    │       └── toolbar
    │           └── toolbar.component.html
    └── index.html`

**Comment by mgechev** [comment] 2016-06-01 07:42
Do you get any errors by running `npm run build.dev`?

**Comment by ShurikAg** [comment] 2016-06-01 07:43
Only these:

/Users/ShurikAg/Dev/angular2/priz-fe/src/client/app/app.component.ts
      line 2  col 29  unused variable: 'Routes'
      line 4  col 9   unused variable: 'HomeComponent'
      line 4  col 29  " should be '

    ✖ 3 errors


/Users/ShurikAg/Dev/angular2/priz-fe/tools/tasks/project/build.html_scss.ts
      line 11  col 7  unused variable: 'cleanCss'

    ✖ 1 error

**Comment by ShurikAg** [comment] 2016-06-01 07:47
Also, when I am trying to use new routes I am getting this issue:
http://prntscr.com/baww4e
It feels like related.

**Comment by ShurikAg** [comment] 2016-06-01 07:56
So, all the IDE warnings are now gone. However, I am back to the same issue of not reloading one code change.

**Comment by NathanielMalca** [comment] 2016-06-01 09:27
same here . this is  a problem that is around for quite a while now

**Comment by NathanielMalca** [comment] 2016-06-01 09:34
this is what i get on firefox debug tools

09:30:15.186 Error: patchProperty/desc.set/wrapFn@http://localhost:5555/node_modules/zone.js/dist/zone.js?1464773410245:769:27
	Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1464773410245:356:24
	Zone</Zone</Zone.prototype.runTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1464773410245:256:29
	ZoneTask/this.invoke@http://localhost:5555/node_modules/zone.js/dist/zone.js?1464773410245:423:29
	
	Error loading http://localhost:5555/node_modules/angular2/package.json
	Error loading http://localhost:5555/app/UserManagement/components/user-management.component.js as "./components/user-management.component" from http://localhost:5555/app/UserManagement/index.js "Report this error at https://github.com/mgechev/angular2-seed/issues"1 user-management:91:7
<anonymous> user-management:91
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke() zone.js:323
Zone</Zone</Zone.prototype.run() zone.js:216
scheduleResolveOrReject/<() zone.js:571
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask() zone.js:356
Zone</Zone</Zone.prototype.runTask() zone.js:256
drainMicroTaskQueue() zone.js:474
ZoneTask/this.invoke() zone.js:426

**Comment by NathanielMalca** [comment] 2016-06-01 09:35
├───dev
│   ├───app
│   │   ├───+about
│   │   ├───+home
│   │   ├───shared
│   │   │   ├───name-list
│   │   │   ├───navbar
│   │   │   └───toolbar
│   │   └───UserManagement
│   │       ├───components
│   │       ├───services
│   │       └───types
│   ├───assets
│   │   ├───css
│   │   ├───fonts
│   │   │   └───fontawesome4.2
│   │   ├───img
│   │   │   └───gradient
│   │   ├───svg
│   │   └───vendors
│   └───css
└───tmp
    └───app
        ├───+about
        ├───+home
        ├───shared
        │   ├───navbar
        │   └───toolbar
        └───UserManagement
            └───components

**Comment by NathanielMalca** [comment] 2016-06-01 09:38
again like @ShurikAg  , when typing npm start everything works welll . if i make a change i get that error that i mentioned.

I'm developing a big project for production and because of this bug i left it pending for a month hoping that the seed will be fixed by that time . sadly it didnt  @mgechev

**Comment by NathanielMalca** [comment] 2016-06-01 09:39
using webstorm on windows env

**Comment by mgechev** [comment] 2016-06-01 11:52
@ShurikAg are you using `@angular/router` or `@angular/router-deprecated`?

**Comment by ShurikAg** [comment] 2016-06-01 15:58
@mgechev `@angular/router`

**Comment by jlberrocal** [comment] 2016-06-01 17:07
i was able to reproduce this error, at least for me it happen when i enabled the TS compiler of WebStorm, after that i get the error on the browser logs

**Comment by ShurikAg** [comment] 2016-06-01 17:21
@jlberrocal I disabled it from the very beginning. I am using IntelliJ

**Comment by jlberrocal** [comment] 2016-06-01 18:03
Yes i used to have it disabled but i enable it by mistake, and after enable it i start to see the error, and no matter if i disable it the error is still there

**Comment by ShurikAg** [comment] 2016-06-02 05:38
Hmmm...
So I removed 'clean.dev' from `build.dev` and everything started to work and refresh.

**Closed** 2016-06-02 06:33 UTC

**Comment by misamae** [comment] 2016-12-15 18:53
I'm experiencing a similar issue. The page fails with the following error after few changes to the code. The strange thing is sometimes it does not happen after the first change in the code. Another strange thing is that the missing page (app/shared/toolbar/index.js) does not exist on in project. I deleted it. Also, this is my setup: 

1. webstorm with typescript compiler disabled
2. I based my project on this seed project


Unhandled Promise rejection: (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/app/shared/toolbar/index.js
	Error: XHR error (404 Not Found) loading http://localhost:5555/app/shared/toolbar/index.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1481827734615:647:29)
	    at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1481827734615:236:37)
	    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1481827734615:136:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1481827734615:304:33)
	Error loading http://localhost:5555/app/shared/toolbar/index.js as "./toolbar/index" from http://localhost:5555/app/shared/shared.module.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/app/shared/toolbar/index.js(…) (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/app/shared/toolbar/index.js
	Error: XHR error (404 Not Found) loading http://localhost:5555/app/shared/toolbar/index.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1481827734615:647:29)
	    at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1481827734615:236:37)
	    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1481827734615:136:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1481827734615:304:33)
	Error loading http://localhost:5555/app/shared/toolbar/index.js as
